-- --------------------------------------------------------
-- Host:                         172.18.144.38
-- Server version:               8.0.31 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.4.0.6659
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table samhall.fix_district
CREATE TABLE IF NOT EXISTS `fix_district` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SProvince` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  `SDistrict` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  `Province` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  `District` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Index 2` (`SDistrict`,`SProvince`)
) ENGINE=InnoDB AUTO_INCREMENT=2054 DEFAULT CHARSET=utf8mb3 COMMENT='an table for automaticaly change district names when importing data';

-- Dumping data for table samhall.fix_district: ~325 rows (approximately)
INSERT INTO `fix_district` (`id`, `SProvince`, `SDistrict`, `Province`, `District`) VALUES
	(1534, 'Fyn/Langeland', '28', 'Fyn', ''),
	(1535, 'Fyn/Langeland', '29', 'Fyn', ''),
	(1536, 'Fyn/Langeland', '30', 'Fyn', ''),
	(1537, 'Fyn/Langeland', '31', 'Fyn', ''),
	(1538, 'Fyn/Langeland', '32', 'Fyn', ''),
	(1539, 'Fyn/Langeland', '33', 'Ærø', 'Ærø'),
	(1540, 'Fyn/Langeland', '34', 'Langeland', 'Langeland'),
	(1541, 'Lolland, Falster & Møn', 'TBU 35', 'Lolland', 'Lolland'),
	(1542, 'Lolland, Falster & Møn', 'TBU 36', 'Lolland', ''),
	(1543, 'Lolland, Falster & Møn', 'TBU 37', 'Falster', 'Guldborgsund'),
	(1544, 'Lolland, Falster & Møn', 'TBU 38', 'Møn', 'Vordingborg'),
	(1545, 'Lolland/Falster/Møn', '35', 'Lolland', 'Lolland'),
	(1546, 'Lolland/Falster/Møn', '36', 'Lolland', ''),
	(1547, 'Lolland/Falster/Møn', '37', 'Falster', 'Guldborgsund'),
	(1548, 'Lolland/Falster/Møn', '38', 'Møn', 'Vordingborg'),
	(1549, 'Lolland/Falster/Møn', 'TBU 35', 'Lolland', 'Lolland'),
	(1550, 'Lolland/Falster/Møn', 'TBU 36', 'Lolland', ''),
	(1551, 'Lolland/Falster/Møn', 'TBU 37', 'Falster', 'Guldborgsund'),
	(1552, 'Lolland/Falster/Møn', 'TBU 38', 'Møn', 'Vordingborg'),
	(1554, 'Blekinge', 'Nätraby', 'Blekinge', 'Nättraby'),
	(1555, 'Blekinge', 'Olofström', 'Blekinge', 'Jämshög'),
	(1557, 'Bohuslän', 'Fjällbacka', 'Bohuslän', 'Kville'),
	(1558, 'Bohuslän', 'Hunnebostrand', 'Bohuslän', 'Tossene'),
	(1560, 'Bohuslän', 'Laneryr', 'Bohuslän', 'Lane-Ryr'),
	(1561, 'Bohuslän', 'Lur & Tanum', 'Bohuslän', ''),
	(1564, 'Bohuslän', 'Ske', 'Bohuslän', 'Skee'),
	(1565, 'Bohuslän', 'Smögen', 'Bohuslän', 'Kungshamn'),
	(1567, 'Dalarna', 'Sollerö', 'Dalarna', 'Sollerön'),
	(1568, 'Dalsland', 'Gunnarsnäs (Dalskog)', 'Dalsland', 'Gunnarsnäs'),
	(1569, 'Dalsland', 'Tissleskog', 'Dalsland', 'Tisselskog'),
	(1570, 'Dalsland', 'Ödsköld', 'Dalsland', 'Ödskölt'),
	(1571, 'Gotland', 'Butle', 'Gotland', 'Buttle'),
	(1574, 'Gotland', 'hanvar', 'Gotland', 'Hangvar'),
	(1575, 'Gotland', 'Hörsne [med Bara]', 'Gotland', 'Hörsne'),
	(1576, 'Gotland', 'Hörsne med Bara', 'Gotland', 'Hörsne'),
	(1577, 'Gotland', 'Levede', 'Gotland', 'Levide'),
	(1579, 'Gotland', 'Vsby', 'Gotland', 'Visby'),
	(1582, 'Gästrikland', 'Heliga Trefaldighet', 'Gästrikland', 'Gävle'),
	(1583, 'Gästrikland', 'Hofors', 'Gästrikland', 'Torsåker'),
	(1585, 'Gästrikland', 'Staffan', 'Gästrikland', 'Gävle'),
	(1587, 'Gästrikland', 'Åmot', 'Gästrikland', 'Ockelbo'),
	(1592, 'Halland', 'Lindberga', 'Halland', 'Lindberg'),
	(1593, 'Halland', 'Oskarsström', 'Halland', 'Enslöv'),
	(1594, 'Halland', 'Oskarström', 'Halland', 'Enslöv'),
	(1598, 'Hälsingland', 'Hybo', 'Hälsingland', 'Ljusdal'),
	(1599, 'Hälsingland', 'Kårböle', 'Hälsingland', 'Färila'),
	(1600, 'Hälsingland', 'Lillhärdal', 'Härjedalen', 'Lillhärdal'),
	(1601, 'Hälsingland', 'Ljusne', 'Hälsingland', 'Söderala'),
	(1603, 'Hälsingland', 'Segelsta', 'Hälsingland', 'Segersta'),
	(1604, 'Hälsingland', 'Tuna', 'Hälsingland', 'Hälsingtuna'),
	(1606, 'Härjedalen', 'Linsäll', 'Härjedalen', 'Linsell'),
	(1608, 'Härjedalen', 'Ljusnedal', 'Härjedalen', 'Tännäs'),
	(1611, 'Härjedalen', 'Ytterhogdal', 'Hälsingland', 'Ytterhogdal'),
	(1612, 'Härjedalen', 'Ängersjö', 'Hälsingland', 'Ängersjö'),
	(1614, 'Jämtland', 'Gillhov', 'Jämtland', 'Hackås'),
	(1615, 'Jämtland', 'Norderön', 'Jämtland', 'Norderö'),
	(1616, 'Jämtland', 'Rödö', 'Jämtland', 'Rödön'),
	(1617, 'Jämtland', 'Storlien', 'Jämtland', 'Åre'),
	(1619, 'Jämtland', 'Torvalla', 'Jämtland', 'Brunflo'),
	(1620, 'Jämtland', 'Ytterhogdal', 'Hälsingland', 'Ytterhogdal'),
	(1621, 'Jämtland', 'Åsarna', 'Jämtland', 'Åsarne'),
	(1622, 'Lule lappmark', 'Hakkas', 'Lule lappmark', 'Gällivare'),
	(1624, 'Lule lappmark', 'Kvikkjokk', 'Lule lappmark', 'Jokkmokk'),
	(1625, 'Lule lappmark', 'Malmberget', 'Lule lappmark', 'Gällivare'),
	(1626, 'Lule lappmark', 'Nilivaara', 'Lule lappmark', 'Gällivare'),
	(1627, 'Lule lappmark', 'Porjus', 'Lule lappmark', 'Jokkmokk'),
	(1629, 'Lule lappmark', 'Vuollerim', 'Lule lappmark', 'Jokkmokk'),
	(1630, 'Lycksele lappmark', 'Björksele', 'Lycksele lappmark', 'Lycksele'),
	(1631, 'Lycksele lappmark', 'Gargnäs', 'Lycksele lappmark', 'Sorsele'),
	(1637, 'Medelpad', 'Indals-Liden', 'Medelpad', 'Liden'),
	(1640, 'Norrbotten', 'Boden', 'Norrbotten', 'Överluleå'),
	(1641, 'Norrbotten', 'Gunnarsbyn', 'Norrbotten', 'Råneå'),
	(1642, 'Norrbotten', 'Haparanda', 'Norrbotten', 'Nedertorneå'),
	(1643, 'Norrbotten', 'Haparanda / Nedertorneå', 'Norrbotten', 'Nedertorneå'),
	(1644, 'Norrbotten', 'Haparande-Nedertorneå', 'Norrbotten', 'Nedertorneå'),
	(1646, 'Norrbotten', 'Kalix', 'Norrbotten', 'Nederkalix'),
	(1647, 'Norrbotten', 'Karesuando', 'Torne lappmark', 'Karesuando'),
	(1648, 'Norrbotten', 'Karl Gustavs', 'Norrbotten', 'Karl Gustav'),
	(1649, 'Norrbotten', 'Karl-Gustav', 'Norrbotten', 'Karl Gustav'),
	(1650, 'Norrbotten', 'Markbygden', 'Norrbotten', 'Piteå'),
	(1651, 'Norrbotten', 'Morjärv', 'Norrbotten', 'Töre'),
	(1652, 'Norrbotten', 'Morjärv kbfd', 'Norrbotten', 'Töre'),
	(1653, 'Norrbotten', 'Morjärvs kbfd', 'Norrbotten', 'Töre'),
	(1654, 'Norrbotten', 'Muonionalusta', 'Norrbotten', 'Pajala'),
	(1655, 'Norrbotten', 'Nedertorneå- Haparanda', 'Norrbotten', 'Nedertorneå'),
	(1656, 'Norrbotten', 'Nedertorneå-Haparanda', 'Norrbotten', 'Nedertorneå'),
	(1657, 'Norrbotten', 'Pite', 'Norrbotten', 'Piteå'),
	(1658, 'Norrbotten', 'Piteå l', 'Norrbotten', 'Piteå'),
	(1659, 'Norrbotten', 'Piteå landsf', 'Norrbotten', 'Piteå'),
	(1660, 'Norrbotten', 'Piteå landsförsamling', 'Norrbotten', 'Piteå'),
	(1661, 'Norrbotten', 'Piteå stad', 'Norrbotten', 'Piteå'),
	(1663, 'Norrbotten', 'Svainstein', 'Norrbotten', 'Övertorneå'),
	(1664, 'Norrbotten', 'Svanstein', 'Norrbotten', 'Övertorneå'),
	(1665, 'Norrbotten', 'Sävast', 'Norrbotten', 'Överluleå'),
	(1666, 'Norrbotten', 'Töre kbfd o sn', 'Norrbotten', 'Töre'),
	(1667, 'Norrbotten', 'Töre Morjärv kfbd', 'Norrbotten', 'Töre'),
	(1668, 'Norrbotten', 'Örnäset', 'Norrbotten', 'Nederluleå'),
	(1674, 'Närke', 'Adolfsberg', 'Närke', 'Örebro'),
	(1677, 'Närke', 'Boo', 'Närke', 'Bo'),
	(1679, 'Närke', 'Frötuna', 'Närke', 'Götlunda'),
	(1681, 'Närke', 'Jötlunda', 'Närke', 'Götlunda'),
	(1683, 'Närke', 'Kräklinge', 'Närke', 'Kräcklinge'),
	(1689, 'Närke', 'Laxå', 'Närke', 'Ramundeboda'),
	(1690, 'Närke', 'Skagerhult', 'Närke', 'Skagershult'),
	(1700, 'Skåne', 'Arkelstorp', 'Skåne', 'Oppmanna'),
	(1703, 'Skåne', 'Fagerhult', 'Skåne', 'Skånes-Fagerhult'),
	(1704, 'Skåne', 'Falsterbo', 'Skåne', 'Skanör med Falsterbo'),
	(1705, 'Skåne', 'Falsterbo / Skanör', 'Skåne', 'Skanör med Falsterbo'),
	(1706, 'Skåne', 'Fosie', 'Skåne', 'Malmö'),
	(1707, 'Skåne', 'Klippan', 'Skåne', 'Gråmanstorp'),
	(1708, 'Skåne', 'Gässie', 'Skåne', 'Gessie'),
	(1710, 'Skåne', 'Hyllie', 'Skåne', 'Malmö'),
	(1711, 'Skåne', 'Hälsingborg', 'Skåne', 'Helsingborg'),
	(1713, 'Skåne', 'Limhamn', 'Skåne', 'Malmö'),
	(1716, 'Skåne', 'Mellby', 'Skåne', ''),
	(1718, 'Skåne', 'Raus', 'Skåne', 'Helsingborg'),
	(1719, 'Skåne', 'S:t Ibb', 'Skåne', 'Sankt Ibb'),
	(1720, 'Skåne', 'S:t Olof', 'Skåne', 'Sankt Olof'),
	(1721, 'Skåne', 'Sankt Peters kloster', 'Skåne', 'Lund'),
	(1722, 'Skåne', 'Skanör', 'Skåne', 'Skanör med Falsterbo'),
	(1723, 'Skåne', 'Skanör m. Falsterbo', 'Skåne', 'Skanör med Falsterbo'),
	(1725, 'Skåne', 'Staffanstorp', 'Skåne', 'Brågarp'),
	(1727, 'Skåne', 'Tomelilla', 'Skåne', 'Tryde'),
	(1730, 'Skåne', 'Vindslöv', 'Skåne', 'Vinslöv'),
	(1731, 'Skåne', 'Vitemölla', 'Skåne', 'Vitaby'),
	(1733, 'Skåne', 'Åstorp', 'Skåne', 'Björnekulla'),
	(1734, 'Skåne', 'Åsum', 'Skåne', ''),
	(1736, 'Småland', 'Alvesta', 'Småland', 'Aringsås'),
	(1737, 'Småland', 'Emmaboda', 'Småland', 'Vissefjärda'),
	(1738, 'Småland', 'Gislaved', 'Småland', 'Båraryd'),
	(1739, 'Småland', 'Hallingsberg', 'Småland', 'Hallingeberg'),
	(1740, 'Småland', 'Hemmesjö med Tegnaby', 'Småland', 'Hemmesjö'),
	(1742, 'Småland', 'Hultsfred', 'Småland', 'Vena'),
	(1743, 'Småland', 'Jönköping / Ljungarum', 'Småland', 'Jönköping'),
	(1744, 'Småland', 'Lessebo', 'Småland', 'Hovmantorp'),
	(1745, 'Småland', 'Ljungarum', 'Småland', 'Jönköping'),
	(1746, 'Småland', 'Ljungby', 'Småland', ''),
	(1747, 'Småland', 'Ljungby, Västra', 'Småland', 'Ljungby [Ljungby kommun]'),
	(1748, 'Småland', 'Ljungby, Östra', 'Småland', 'Ljungby [Kalmar kommun]'),
	(1749, 'Småland', 'Ljungby-G', 'Småland', 'Ljungby [Ljungby kommun]'),
	(1750, 'Småland', 'Ljungby-H', 'Småland', 'Ljungby [Kalmar kommun]'),
	(1751, 'Småland', 'Lockne', 'Småland', 'Locknevi'),
	(1752, 'Småland', 'Målilla med Gårdveda', 'Småland', 'Målilla'),
	(1754, 'Småland', 'Rydaholms', 'Småland', 'Rydaholm'),
	(1755, 'Småland', 'Ryssby', 'Småland', ''),
	(1756, 'Småland', 'Ryssby Västra', 'Småland', 'Ryssby [Ljungby kommun]'),
	(1757, 'Småland', 'Ryssby Östra', 'Småland', 'Ryssby [Kalmar kommun]'),
	(1758, 'Småland', 'Ryssby, Västra', 'Småland', 'Ryssby [Ljungby kommun]'),
	(1759, 'Småland', 'Ryssby, Östra', 'Småland', 'Ryssby [Kalmar kommun]'),
	(1760, 'Småland', 'Ryssby-G', 'Småland', 'Ryssby [Ljungby kommun]'),
	(1761, 'Småland', 'Ryssby-H', 'Småland', 'Ryssby [Kalmar kommun]'),
	(1762, 'Småland', 'S. Sandsjö', 'Småland', 'Södra Sandsjö'),
	(1763, 'Småland', 'Norrahammar', 'Småland', 'Sandseryd'),
	(1764, 'Småland', 'Skillingaryd', 'Småland', 'Tofteryd'),
	(1766, 'Småland', 'Svennarum', 'Småland', 'Svenarum'),
	(1768, 'Småland', 'Visingsborg', 'Småland', 'Visingsö'),
	(1769, 'Småland', 'Voxtorp', 'Småland', ''),
	(1770, 'Småland', 'Voxtorp Västra', 'Småland', 'Voxtorp [Värnamo kommun]'),
	(1771, 'Småland', 'Voxtorp Östra', 'Småland', 'Voxtorp [Kalmar kommun]'),
	(1772, 'Småland', 'Voxtorp, Västra', 'Småland', 'Voxtorp [Värnamo kommun]'),
	(1773, 'Småland', 'Voxtorp, Östra', 'Småland', 'Voxtorp [Kalmar kommun]'),
	(1774, 'Småland', 'Voxtorp-F', 'Småland', 'Voxtorp [Värnamo kommun]'),
	(1775, 'Småland', 'Voxtorp-H', 'Småland', 'Voxtorp [Kalmar kommun]'),
	(1776, 'Småland', 'Voxtorps', 'Småland', ''),
	(1777, 'Småland', 'Älmhult', 'Småland', 'Stenbrohult'),
	(1778, 'Södermanland', 'Allhelgona', 'Södermanland', 'Helgona'),
	(1780, 'Södermanland', 'Brännkyrka', 'Södermanland', 'Stockholm'),
	(1783, 'Södermanland', 'Enskede', 'Södermanland', 'Stockholm'),
	(1784, 'Södermanland', 'Eskilstuna, Kloster', 'Södermanland', 'Eskilstuna'),
	(1786, 'Södermanland', 'Farsta', 'Södermanland', 'Stockholm'),
	(1787, 'Södermanland', 'Flemingsberg', 'Södermanland', 'Huddinge'),
	(1789, 'Södermanland', 'Frustuna - Kattnäs', 'Södermanland', ''),
	(1790, 'Södermanland', 'Frustuna/Kattnäs', 'Södermanland', ''),
	(1791, 'Södermanland', 'Frustuna-Kattnäs', 'Södermanland', ''),
	(1795, 'Södermanland', 'Hägersten', 'Södermanland', 'Stockholm'),
	(1796, 'Södermanland', 'Hällby', 'Södermanland', 'Torshälla'),
	(1798, 'Södermanland', 'Nicolai', 'Södermanland', 'Sankt Nicolai'),
	(1799, 'Södermanland', 'Nikolai', 'Södermanland', 'Sankt Nicolai'),
	(1800, 'Södermanland', 'Saltsjöbaden', 'Södermanland', 'Nacka'),
	(1801, 'Södermanland', 'Sanct Nicolai', 'Södermanland', 'Sankt Nicolai'),
	(1802, 'Södermanland', 'Sankt Mikael', 'Södermanland', 'Huddinge'),
	(1805, 'Södermanland', 'Skarpnäck', 'Södermanland', 'Stockholm'),
	(1806, 'Södermanland', 'Skärholmen', 'Södermanland', 'Huddinge'),
	(1809, 'Södermanland', 'Trosa', 'Södermanland', 'Trosa-Vagnhärad'),
	(1810, 'Södermanland', 'Trosa landsförsamling', 'Södermanland', 'Trosa-Vagnhärad'),
	(1811, 'Södermanland', 'Trosa stadsförsamling', 'Södermanland', 'Trosa-Vagnhärad'),
	(1813, 'Södermanland', 'Trångsund', 'Södermanland', 'Huddinge'),
	(1814, 'Södermanland', 'Tullinge', 'Södermanland', 'Botkyrka'),
	(1815, 'Södermanland', 'Tumba', 'Södermanland', 'Botkyrka'),
	(1818, 'Södermanland', 'Vagnhärad', 'Södermanland', 'Trosa-Vagnhärad'),
	(1819, 'Södermanland', 'Vantör', 'Södermanland', 'Stockholm'),
	(1820, 'Södermanland', 'Vingåker', 'Södermanland', ''),
	(1826, 'Torne lappmark', 'Kiruna', 'Torne lappmark', 'Jukkasjärvi'),
	(1828, 'Torne lappmark', 'Vittangi', 'Torne lappmark', 'Jukkasjärvi'),
	(1829, 'Uppland', 'Barkarby', 'Uppland', 'Järfälla'),
	(1830, 'Uppland', 'Bergshamra', 'Uppland', ''),
	(1831, 'Uppland', 'Björkö', 'Uppland', 'Björkö-Arholma'),
	(1832, 'Uppland', 'Bo', 'Uppland', 'Boo'),
	(1834, 'Uppland', 'Bromma', 'Uppland', 'Stockholm'),
	(1835, 'Uppland', 'Färingsö', 'Uppland', 'Sånga'),
	(1837, 'Uppland', 'Gottsunda', 'Uppland', 'Bondkyrka'),
	(1839, 'Uppland', 'Heliga Trefaldighet', 'Uppland', 'Uppsala'),
	(1841, 'Uppland', 'Husby-Ärlighundra', 'Uppland', 'Husby-Ärlinghundra'),
	(1842, 'Uppland', 'Hässelby', 'Uppland', 'Stockholm'),
	(1843, 'Uppland', 'Jakobsberg', 'Uppland', 'Järfälla'),
	(1844, 'Uppland', 'Kallhäll', 'Uppland', 'Järfälla'),
	(1845, 'Uppland', 'Kista', 'Uppland', 'Spånga'),
	(1847, 'Uppland', 'Ljusterö-Kulla', 'Uppland', 'Ljusterö'),
	(1851, 'Uppland', 'Roslagskulla', 'Uppland', 'Roslags-Kulla'),
	(1852, 'Uppland', 'Råsunda', 'Uppland', 'Solna'),
	(1853, 'Uppland', 'S:t Olof', 'Uppland', 'Sankt Olof'),
	(1854, 'Uppland', 'S:t Per', 'Uppland', 'Sankt Per'),
	(1857, 'Uppland', 'Skutskär', 'Uppland', 'Älvkarleby'),
	(1859, 'Uppland', 'Stockholm, Bromma', 'Uppland', 'Stockholm'),
	(1860, 'Uppland', 'Kungsängen', 'Uppland', 'Stockholms-Näs'),
	(1864, 'Uppland', 'Svinngarn', 'Uppland', 'Svinnegarn'),
	(1865, 'Uppland', 'Söderby Karl', 'Uppland', 'Söderby-Karl'),
	(1866, 'Uppland', 'Tibble', 'Uppland', ''),
	(1868, 'Uppland', 'Viksjö', 'Uppland', 'Järfälla'),
	(1869, 'Uppland', 'Vällingby', 'Uppland', 'Spånga'),
	(1870, 'Uppland', 'Västerled', 'Uppland', 'Stockholm'),
	(1871, 'Uppland', 'Ö. Ryd', 'Uppland', 'Östra Ryd'),
	(1874, 'Uppland', 'Österåker-Östra Ryd', 'Uppland', ''),
	(1877, 'Värmland', 'Deje', 'Värmland', 'Nedre Ullerud'),
	(1879, 'Värmland', 'Karlstads domkyrkoförsamling', 'Värmland', 'Karlstad'),
	(1882, 'Värmland', 'Molkom', 'Värmland', 'Nyed'),
	(1883, 'Värmland', 'Munkfors', 'Värmland', 'Ransäter'),
	(1884, 'Värmland', 'N. Finnskoga', 'Värmland', 'Norra Finnskoga'),
	(1887, 'Värmland', 'Storfors', 'Värmland', 'Kroppa'),
	(1892, 'Västerbotten', 'Boliden', 'Västerbotten', 'Skellefteå'),
	(1894, 'Västerbotten', 'Fällfors', 'Västerbotten', 'Byske'),
	(1896, 'Västerbotten', 'Kalvträsk', 'Västerbotten', 'Burträsk'),
	(1897, 'Västerbotten', 'Kågedalen', 'Västerbotten', 'Skellefteå'),
	(1899, 'Västerbotten', 'Sankt Örjan', 'Västerbotten', 'Skellefteå'),
	(1901, 'Västerbotten', 'Skellefte', 'Västerbotten', 'Skellefteå'),
	(1902, 'Västerbotten', 'Skellefteå landsförsamling', 'Västerbotten', 'Skellefteå'),
	(1906, 'Västerbotten', 'Vindeln', 'Västerbotten', 'Degerfors'),
	(1907, 'Västerbotten', 'Åmsele', 'Västerbotten', 'Degerfors'),
	(1909, 'Västergötland', 'Ale- Skövde', 'Västergötland', 'Ale-Skövde'),
	(1910, 'Västergötland', 'Bitterna', 'Västergötland', ''),
	(1915, 'Västergötland', 'Friggesåker', 'Västergötland', 'Friggeråker'),
	(1917, 'Västergötland', 'Fässbeg', 'Västergötland', 'Mölndal'),
	(1918, 'Västergötland', 'Gunnared', 'Västergötland', 'Angered'),
	(1919, 'Västergötland', 'Gustav-Adolf', 'Västergötland', 'Gustav Adolf'),
	(1920, 'Västergötland', 'Göteborg / Lundby', 'Västergötland', 'Göteborg'),
	(1921, 'Västergötland', 'Kattunga', 'Västergötland', 'Surteby-Kattunga'),
	(1923, 'Västergötland', 'Ljunghems', 'Västergötland', 'Ljunghem'),
	(1924, 'Västergötland', 'Lundby', 'Västergötland', 'Göteborg'),
	(1928, 'Västergötland', 'Råda', 'Västergötland', ''),
	(1929, 'Västergötland', 'Råda, Kållands-', 'Västergötland', 'Råda [Lidköpings kommun]'),
	(1930, 'Västergötland', 'Råda-O', 'Västergötland', 'Råda [Härryda kommun]'),
	(1931, 'Västergötland', 'S:t Peder', 'Västergötland', 'Sankt Peder'),
	(1933, 'Västergötland', 'Sankt Peter', 'Västergötland', 'Sankt Peder'),
	(1935, 'Västergötland', 'Stensjön', 'Västergötland', 'Mölndal'),
	(1936, 'Västergötland', 'Surteby', 'Västergötland', 'Surteby-Kattunga'),
	(1939, 'Västergötland', 'Sävedalen', 'Västergötland', 'Partille'),
	(1940, 'Västergötland', 'Ugglums', 'Västergötland', 'Ugglum'),
	(1941, 'Västergötland', 'Ulricehamns', 'Västergötland', 'Ulricehamn'),
	(1948, 'Västergötland', 'Åsarp', 'Västergötland', ''),
	(1950, 'Västergötland', 'Älvsborg', 'Västergötland', 'Västra Frölunda'),
	(1951, 'Västergötland', 'Örgryte', 'Västergötland', 'Göteborg'),
	(1955, 'Västmanland', 'Guldsmedshyttan', 'Västmanland', 'Linde'),
	(1956, 'Västmanland', 'Hallstahammar', 'Västmanland', 'Svedvi'),
	(1957, 'Västmanland', 'Halstahammar', 'Västmanland', 'Svedvi'),
	(1960, 'Västmanland', 'Kungsör', 'Västmanland', '	Kungs-Barkarö'),
	(1962, 'Västmanland', 'Lundby', 'Västmanland', 'Västerås'),
	(1964, 'Västmanland', 'Nora bergsförsamling', 'Västmanland', 'Nora'),
	(1966, 'Västmanland', 'S:t Ilian', 'Västmanland', 'Västerås'),
	(1968, 'Västmanland', 'Storå', 'Västmanland', 'Linde'),
	(1969, 'Västmanland', 'Surahammar', 'Västmanland', 'Sura'),
	(1971, 'Västmanland', 'Fagersta', 'Västmanland', 'Västanfors'),
	(1972, 'Västmanland', 'Väster-Färnebo', 'Västmanland', 'Västerfärnebo'),
	(1975, 'Ångermanland', 'Frånö', 'Ångermanland', 'Gudmundrå'),
	(1976, 'Ångermanland', 'Kramfors', 'Ångermanland', 'Gudmundrå'),
	(1977, 'Ångermanland', 'Hernösand', 'Ångermanland', 'Härnösand'),
	(1978, 'Ångermanland', 'Hoting', 'Ångermanland', 'Tåsjö'),
	(1979, 'Ångermanland', 'Härnö', 'Ångermanland', 'Härnösand'),
	(1980, 'Ångermanland', 'Härnön', 'Ångermanland', 'Härnösand'),
	(1983, 'Ångermanland', 'Solleftå', 'Ångermanland', 'Sollefteå'),
	(1984, 'Ångermanland', 'Säbro', 'Ångermanland', 'Säbrå'),
	(1988, 'Ångermanland', 'Ådalsliden', 'Ångermanland', 'Ådals-Liden'),
	(1990, 'Åsele lappmark', 'Risbäck', 'Åsele lappmark', 'Dorotea'),
	(1993, 'Öland', 'Bredsätra', 'Öland', 'Bredsättra'),
	(1995, 'Öland', 'Ekby', 'Öland', 'Egby'),
	(1996, 'Öland', 'Kalkstad', 'Öland', 'Torslunda'),
	(1998, 'Öland', 'Repplinge', 'Öland', 'Räpplinge'),
	(1999, 'Öland', 'Stenninge', 'Öland', 'Persnäs'),
	(2000, 'Öland', 'Tveta', 'Öland', 'Torslunda'),
	(2005, 'Östergötland', 'Kullerstads', 'Östergötland', 'Kullerstad'),
	(2010, 'Östergötland', 'S:t Anna', 'Östergötland', 'Sankt Anna'),
	(2011, 'Östergötland', 'S:t Johannes', 'Östergötland', 'Norrköping'),
	(2012, 'Östergötland', 'Sankt Johannes', 'Östergötland', 'Norrköping'),
	(2013, 'Östergötland', 'Sankt Lars', 'Östergötland', 'Linköping'),
	(2014, 'Östergötland', 'Styrestad', 'Östergötland', 'Styrstad'),
	(2017, 'Östergötland', 'Valdemarsvik', 'Östergötland', 'Ringarum'),
	(2020, 'Östergötland', 'Vreta', 'Östergötland', 'Vreta kloster'),
	(2022, 'Östergötland', 'Åtvidaberg', 'Östergötland', 'Åtvid'),
	(2024, 'Östergötland', 'Östra Eneby', 'Östergötland', 'Norrköping'),
	(2026, 'Norrbotten', 'Älvsbyn', 'Norrbotten', 'Älvsby'),
	(2027, '	Södermanland / Uppland', 'Stockholm', '', 'Stockholm'),
	(2028, 'Norrbotten', 'Luleå', 'Norrbotten', 'Nederluleå'),
	(2029, 'Ångermanland', 'Örnsköldsvik', 'Ångermanland', 'Själevad'),
	(2030, 'Hälsingland', 'Hudiksvall', 'Hälsingland', 'Hälsingtuna'),
	(2031, 'Dalarna', 'Falun', 'Dalarna', 'Stora Kopparberg'),
	(2032, 'Dalarna', 'Borlänge', 'Dalarna', 'Stora Tuna'),
	(2033, 'Dalarna', 'Kopparberg', 'Dalarna', 'Stora Tuna'),
	(2034, 'Värmland', 'Hagfors', 'Värmland', 'Norra Råda'),
	(2035, 'Värmland', 'Forshaga', 'Värmland', 'Grava'),
	(2036, 'Västmanland', 'Lindesberg', 'Västmanland', 'Linde'),
	(2037, 'Västmanland', 'Frövi', 'Västmanland', 'Näsby'),
	(2038, 'Uppland', 'Östhammar', 'Uppland', 'Börstil'),
	(2039, 'Uppland', 'Öregrund', 'Uppland', 'Börstil'),
	(2040, 'Uppland', 'Husby-Sjuhundra', 'Uppland', 'Husby-Lyhundra'),
	(2041, 'Södermanland', 'Oxelösund', 'Södermanland', 'Sankt Nicolai'),
	(2042, 'Södermanland', 'Trosa stad', 'Södermanland', 'Trosa-Vagnhärad'),
	(2043, 'Bohuslän', 'Lysekil', 'Bohuslän', 'Lyse'),
	(2044, 'Västergötland', 'Grästorp', 'Västergötland', 'Tengene'),
	(2045, 'Västergötland', 'Tibro', 'Västergötland', 'Kyrkefalla'),
	(2046, 'Västergötland', 'Töreboda', 'Västergötland', 'Björkäng'),
	(2047, 'Västergötland', 'Varnhem', 'Västergötland', 'Skarke'),
	(2048, 'Västergötland', 'Limmared', 'Västergötland', 'Södra Åsarp'),
	(2049, 'Skåne', 'Munka Ljungby', 'Skåne', 'Munka-Ljungby'),
	(2051, 'Gästrikland', 'Sandviken', 'Gästrikland', 'Högbo'),
	(2052, 'Värmland', 'Kristinehamn', 'Värmland', 'Varnum'),
	(2053, 'Värmland', 'Filipstad', 'Värmland', 'Färnebo');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
