-- --------------------------------------------------------
-- Host:                         172.18.144.38
-- Server version:               8.0.31 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.2.0.6576
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table samhall.fix_district
CREATE TABLE IF NOT EXISTS `fix_district` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SProvince` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  `SDistrict` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  `Province` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  `District` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_swedish_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `Sprovince` (`SProvince`),
  KEY `SDistrict` (`SDistrict`)
) ENGINE=InnoDB AUTO_INCREMENT=2025 DEFAULT CHARSET=utf8mb3 COMMENT='an table for automaticaly change district names when importing data';

-- Dumping data for table samhall.fix_district: ~491 rows (approximately)
INSERT INTO `fix_district` (`id`, `SProvince`, `SDistrict`, `Province`, `District`) VALUES
	(1534, 'Fyn/Langeland', '28', 'Fyn', ''),
	(1535, 'Fyn/Langeland', '29', 'Fyn', ''),
	(1536, 'Fyn/Langeland', '30', 'Fyn', ''),
	(1537, 'Fyn/Langeland', '31', 'Fyn', ''),
	(1538, 'Fyn/Langeland', '32', 'Fyn', ''),
	(1539, 'Fyn/Langeland', '33', 'Ærø', 'Ærø'),
	(1540, 'Fyn/Langeland', '34', 'Langeland', 'Langeland'),
	(1541, 'Lolland, Falster & Møn', 'TBU 35', 'Lolland', 'Lolland'),
	(1542, 'Lolland, Falster & Møn', 'TBU 36', 'Lolland', ''),
	(1543, 'Lolland, Falster & Møn', 'TBU 37', 'Falster', 'Guldborgsund'),
	(1544, 'Lolland, Falster & Møn', 'TBU 38', 'Møn', 'Vordingborg'),
	(1545, 'Lolland/Falster/Møn', '35', 'Lolland', 'Lolland'),
	(1546, 'Lolland/Falster/Møn', '36', 'Lolland', ''),
	(1547, 'Lolland/Falster/Møn', '37', 'Falster', 'Guldborgsund'),
	(1548, 'Lolland/Falster/Møn', '38', 'Møn', 'Vordingborg'),
	(1549, 'Lolland/Falster/Møn', 'TBU 35', 'Lolland', 'Lolland'),
	(1550, 'Lolland/Falster/Møn', 'TBU 36', 'Lolland', ''),
	(1551, 'Lolland/Falster/Møn', 'TBU 37', 'Falster', 'Guldborgsund'),
	(1552, 'Lolland/Falster/Møn', 'TBU 38', 'Møn', 'Vordingborg'),
	(1553, 'Blekinge', 'Lösen o Augerum', 'Blekinge', ''),
	(1554, 'Blekinge', 'Nätraby', 'Blekinge', 'Nättraby'),
	(1555, 'Blekinge', 'Olofström', 'Blekinge', 'Jämshög'),
	(1556, 'Blekinge', 'Viby', '', ''),
	(1557, 'Bohuslän', 'Fjällbacka', 'Bohuslän', 'Kville'),
	(1558, 'Bohuslän', 'Hunnebostrand', 'Bohuslän', 'Tossene'),
	(1559, 'Bohuslän', 'Kungshamn', 'Bohuslän', 'Askum'),
	(1560, 'Bohuslän', 'Laneryr', 'Bohuslän', 'Lane-Ryr'),
	(1561, 'Bohuslän', 'Lur & Tanum', 'Bohuslän', ''),
	(1562, 'Bohuslän', 'Misterhult', '', ''),
	(1563, 'Bohuslän', 'Norra Råda', '', ''),
	(1564, 'Bohuslän', 'Ske', 'Bohuslän', 'Skee'),
	(1565, 'Bohuslän', 'Smögen', 'Bohuslän', 'Askum'),
	(1566, 'Bohuslän', 'Uddeval?a', 'Bohuslän', 'Uddevalla'),
	(1567, 'Dalarna', 'Sollerö', 'Dalarna', 'Sollerön'),
	(1568, 'Dalsland', 'Gunnarsnäs (Dalskog)', 'Dalsland', 'Gunnarsnäs'),
	(1569, 'Dalsland', 'Tissleskog', 'Dalsland', 'Tisselskog'),
	(1570, 'Dalsland', 'Ödsköld', 'Dalsland', 'Ödskölt'),
	(1571, 'Gotland', 'Butle', 'Gotland', 'Buttle'),
	(1572, 'Gotland', 'Böda', '', ''),
	(1573, 'Gotland', 'Gräsö', '', ''),
	(1574, 'Gotland', 'hanvar', 'Gotland', 'Hangvar'),
	(1575, 'Gotland', 'Hörsne [med Bara]', 'Gotland', 'Hörsne'),
	(1576, 'Gotland', 'Hörsne med Bara', 'Gotland', 'Hörsne'),
	(1577, 'Gotland', 'Levede', 'Gotland', 'Levide'),
	(1578, 'Gotland', 'Vickleby', '', ''),
	(1579, 'Gotland', 'Vsby', 'Gotland', 'Visby'),
	(1580, 'Gästrikland', 'Bollnäs', '', ''),
	(1581, 'Gästrikland', 'Gävla', 'Gästrikland', 'Gävle'),
	(1582, 'Gästrikland', 'Heliga Trefaldighet', 'Gästrikland', 'Gävle'),
	(1583, 'Gästrikland', 'Hofors', '', ''),
	(1584, 'Gästrikland', 'Högbo', '', ''),
	(1585, 'Gästrikland', 'Staffan', 'Gästrikland', 'Gävle'),
	(1586, 'Gästrikland', 'Strömsbro', '', ''),
	(1587, 'Gästrikland', 'Åmot', '', ''),
	(1588, 'Gästrikland', 'Älvkarleby', '', ''),
	(1589, 'Halland', 'Askim', '', ''),
	(1590, 'Halland', 'Göteborg', '', ''),
	(1591, 'Halland', 'Härslöv', '', ''),
	(1592, 'Halland', 'Lindberga', 'Halland', 'Lindberg'),
	(1593, 'Halland', 'Oskarsström', 'Halland', 'Enslöv'),
	(1594, 'Halland', 'Oskarström', 'Halland', 'Enslöv'),
	(1595, 'Halland', 'Röddinge', '', ''),
	(1596, 'Halland', 'Stora Hammar', '', ''),
	(1597, 'Halland', 'Östergarn', '', ''),
	(1598, 'Hälsingland', 'Hybo', '', ''),
	(1599, 'Hälsingland', 'Kårböle', '', ''),
	(1600, 'Hälsingland', 'Lillhärdal', 'Härjedalen', 'Lillhärdal'),
	(1601, 'Hälsingland', 'Ljusne', '', ''),
	(1602, 'Hälsingland', 'Sandarne', '', ''),
	(1603, 'Hälsingland', 'Segelsta', 'Hälsingland', 'Segersta'),
	(1604, 'Hälsingland', 'Tuna', '', ''),
	(1605, 'Härjedalen', 'Kåfjord', '', ''),
	(1606, 'Härjedalen', 'Linsäll', 'Härjedalen', 'Linsell'),
	(1607, 'Härjedalen', 'Ljusdal', '', ''),
	(1608, 'Härjedalen', 'Ljusnedal', '', ''),
	(1609, 'Härjedalen', 'Medelplana', '', ''),
	(1610, 'Härjedalen', 'Storfjord', '', ''),
	(1611, 'Härjedalen', 'Ytterhogdal', 'Hälsingland', 'Ytterhogdal'),
	(1612, 'Härjedalen', 'Ängersjö', 'Hälsingland', 'Ängersjö'),
	(1613, 'Jämtland', 'Bräcke-Nyhem', '', ''),
	(1614, 'Jämtland', 'Gillhov', 'Jämtland', 'Hackås'),
	(1615, 'Jämtland', 'Norderön', 'Jämtland', 'Norderö'),
	(1616, 'Jämtland', 'Rödö', 'Jämtland', 'Rödön'),
	(1617, 'Jämtland', 'Storlien', 'Jämtland', 'Åre'),
	(1618, 'Jämtland', 'Storsjö', '', ''),
	(1619, 'Jämtland', 'Torvalla', '', ''),
	(1620, 'Jämtland', 'Ytterhogdal', 'Hälsingland', 'Ytterhogdal'),
	(1621, 'Jämtland', 'Åsarna', 'Jämtland', 'Åsarne'),
	(1622, 'Lule lappmark', 'Hakkas', 'Lule lappmark', 'Gällivare'),
	(1623, 'Lule lappmark', 'Jukkasjärvi', '', ''),
	(1624, 'Lule lappmark', 'Kvikkjokk', 'Lule lappmark', 'Jokkmokk'),
	(1625, 'Lule lappmark', 'Malmberget', 'Lule lappmark', 'Gällivare'),
	(1626, 'Lule lappmark', 'Nilivaara', 'Lule lappmark', 'Gällivare'),
	(1627, 'Lule lappmark', 'Porjus', 'Lule lappmark', 'Jokkmokk'),
	(1628, 'Lule lappmark', 'Torp', '', ''),
	(1629, 'Lule lappmark', 'Vuollerim', 'Lule lappmark', 'Jokkmokk'),
	(1630, 'Lycksele lappmark', 'Björksele', 'Lycksele lappmark', 'Lycksele'),
	(1631, 'Lycksele lappmark', 'Gargnäs', 'Lycksele lappmark', 'Sorsele'),
	(1632, 'Lycksele lappmark', 'Tärna ?', '', ''),
	(1633, 'Lycksele lappmark', 'Vilhelmina', '', ''),
	(1634, 'Lycksele lappmark', 'Vindeln', '', ''),
	(1635, 'Medelpad', 'Arbrå', '', ''),
	(1636, 'Medelpad', 'Härnösand', '', ''),
	(1637, 'Medelpad', 'Indals-Liden', 'Medelpad', 'Liden'),
	(1638, 'Medelpad', 'Indals-Liden / Ljustorp', '', ''),
	(1639, 'Medelpad', 'Säbrå', '', ''),
	(1640, 'Norrbotten', 'Boden', 'Norrbotten', 'Överluleå'),
	(1641, 'Norrbotten', 'Gunnarsbyn', 'Norrbotten', 'Råneå'),
	(1642, 'Norrbotten', 'Haparanda', 'Norrbotten', 'Nedertorneå'),
	(1643, 'Norrbotten', 'Haparanda / Nedertorneå', 'Norrbotten', 'Nedertorneå'),
	(1644, 'Norrbotten', 'Haparande-Nedertorneå', 'Norrbotten', 'Nedertorneå'),
	(1645, 'Norrbotten', 'Jokkmokk', '', ''),
	(1646, 'Norrbotten', 'Kalix', '', ''),
	(1647, 'Norrbotten', 'Karesuando', '', ''),
	(1648, 'Norrbotten', 'Karl Gustavs', 'Norrbotten', 'Karl Gustav'),
	(1649, 'Norrbotten', 'Karl-Gustav', 'Norrbotten', 'Karl Gustav'),
	(1650, 'Norrbotten', 'Markbygden', 'Norrbotten', 'Piteå'),
	(1651, 'Norrbotten', 'Morjärv', 'Norrbotten', 'Töre'),
	(1652, 'Norrbotten', 'Morjärv kbfd', 'Norrbotten', 'Töre'),
	(1653, 'Norrbotten', 'Morjärvs kbfd', 'Norrbotten', 'Töre'),
	(1654, 'Norrbotten', 'Muonionalusta', 'Norrbotten', 'Pajala'),
	(1655, 'Norrbotten', 'Nedertorneå- Haparanda', 'Norrbotten', 'Nedertorneå'),
	(1656, 'Norrbotten', 'Nedertorneå-Haparanda', 'Norrbotten', 'Nedertorneå'),
	(1657, 'Norrbotten', 'Pite', 'Norrbotten', 'Piteå'),
	(1658, 'Norrbotten', 'Piteå l', 'Norrbotten', 'Piteå'),
	(1659, 'Norrbotten', 'Piteå landsf', 'Norrbotten', 'Piteå'),
	(1660, 'Norrbotten', 'Piteå landsförsamling', 'Norrbotten', 'Piteå'),
	(1661, 'Norrbotten', 'Piteå stad', 'Norrbotten', 'Piteå'),
	(1662, 'Norrbotten', 'Silvberg', '', ''),
	(1663, 'Norrbotten', 'Svainstein', 'Norrbotten', 'Övertorneå'),
	(1664, 'Norrbotten', 'Svanstein', 'Norrbotten', 'Övertorneå'),
	(1665, 'Norrbotten', 'Sävast', 'Norrbotten', 'Överluleå'),
	(1666, 'Norrbotten', 'Töre kbfd o sn', 'Norrbotten', 'Töre'),
	(1667, 'Norrbotten', 'Töre Morjärv kfbd', 'Norrbotten', 'Töre'),
	(1668, 'Norrbotten', 'Örnäset', 'Norrbotten', 'Luleå'),
	(1669, 'Norrbotten', 'Överklaix', 'Norrbotten', 'Överkalix'),
	(1670, 'Norrbotten', 'Överklalix', 'Norrbotten', 'Överkalix'),
	(1671, 'Norrbotten', 'Överklix', 'Norrbotten', 'Överkalix'),
	(1672, 'Norrbotten', 'Övertorneå ?', '', ''),
	(1673, 'Norrbotten', 'Övertårneå', 'Norrbotten', 'Övertorneå'),
	(1674, 'Närke', 'Adolfsberg', 'Närke', 'Örebro'),
	(1675, 'Närke', 'Almby', 'Närke', 'Örebro'),
	(1676, 'Närke', 'Bodum', '', ''),
	(1677, 'Närke', 'Boo', 'Närke', 'Bo'),
	(1678, 'Närke', 'Eker', 'Närke', 'Örebro'),
	(1679, 'Närke', 'Frötuna', '', ''),
	(1680, 'Närke', 'Hällefors', '', ''),
	(1681, 'Närke', 'Jötlunda', 'Närke', 'Götlunda'),
	(1682, 'Närke', 'Kristbo', '', ''),
	(1683, 'Närke', 'Kräklinge', 'Närke', 'Kräcklinge'),
	(1684, 'Närke', 'Lillkyrka-Ödeby', '', ''),
	(1685, 'Närke', 'Längbro', 'Närke', 'Örebro'),
	(1686, 'Närke', 'Längbro / Ånsta', 'Närke', 'Örebro'),
	(1687, 'Närke', 'Nora', '', ''),
	(1688, 'Närke', 'Ramsberg', '', ''),
	(1689, 'Närke', 'Ramundeboda', 'Närke', 'Laxå'),
	(1690, 'Närke', 'Skagerhult', 'Närke', 'Skagershult'),
	(1691, 'Närke', 'Vintros', 'Närke', 'Vintrosa'),
	(1692, 'Närke', 'Ånsta', 'Närke', 'Örebro'),
	(1693, 'Pite lappmark', '2', '', ''),
	(1694, 'Pite lappmark', 'Arvidsajur', 'Pite lappmark', 'Arvidsjaur'),
	(1695, 'Pite lappmark', 'Dorotea', '', ''),
	(1696, 'Pite lappmark', 'Jokkmokk', '', ''),
	(1697, 'Pite lappmark', 'Jukkasjärvi', '', ''),
	(1698, 'Pite lappmark', 'Malå', '', ''),
	(1699, 'Skåne', 'Allhelgona', '', ''),
	(1700, 'Skåne', 'Arkelstorp', 'Skåne', 'Oppmanna'),
	(1701, 'Skåne', 'Bjärred', '', ''),
	(1702, 'Skåne', 'Borlunda-Skeglinge', '', ''),
	(1703, 'Skåne', 'Fagerhult', 'Skåne', 'Skånes-Fagerhult'),
	(1704, 'Skåne', 'Falsterbo', 'Skåne', 'Skanör m. Falsterbo'),
	(1705, 'Skåne', 'Falsterbo / Skanör', 'Skåne', 'Skanör m. Falsterbo'),
	(1706, 'Skåne', 'Fosie', 'Skåne', 'Malmö'),
	(1707, 'Skåne', 'Gråmanstorp', 'Skåne', 'Klippan'),
	(1708, 'Skåne', 'Gässie', 'Skåne', 'Gessie'),
	(1709, 'Skåne', 'Husie', 'Skåne', 'Malmö'),
	(1710, 'Skåne', 'Hyllie', 'Skåne', 'Malmö'),
	(1711, 'Skåne', 'Hälsingborg', 'Skåne', 'Helsingborg'),
	(1712, 'Skåne', 'Lackalänga-Stävie', '', ''),
	(1713, 'Skåne', 'Limhamn', 'Skåne', 'Malmö'),
	(1714, 'Skåne', 'Malnö', 'Skåne', 'Malmö'),
	(1715, 'Skåne', 'Maria', '', ''),
	(1716, 'Skåne', 'Mellby', '', ''),
	(1717, 'Skåne', 'Norra Åsum', 'Skåne', 'Kristianstad'),
	(1718, 'Skåne', 'Raus', 'Skåne', 'Helsingborg'),
	(1719, 'Skåne', 'S:t Ibb', 'Skåne', 'Sankt Ibb'),
	(1720, 'Skåne', 'S:t Olof', 'Skåne', 'Sankt Olof'),
	(1721, 'Skåne', 'Sankt Peters kloster', 'Skåne', 'Lund'),
	(1722, 'Skåne', 'Skanör', 'Skåne', 'Skanör m. Falsterbo'),
	(1723, 'Skåne', 'Skanör med Falsterbo', 'Skåne', 'Skanör m. Falsterbo'),
	(1724, 'Skåne', 'Sorunda', '', ''),
	(1725, 'Skåne', 'Staffanstorp', '', ''),
	(1726, 'Skåne', 'Södra Sallerup', 'Skåne', 'Malmö'),
	(1727, 'Skåne', 'Tomelilla', 'Skåne', 'Tryde'),
	(1728, 'Skåne', 'Torn', '', ''),
	(1729, 'Skåne', 'Uddevalla', '', ''),
	(1730, 'Skåne', 'Vindslöv', 'Skåne', 'Vinslöv'),
	(1731, 'Skåne', 'Vitemölla', 'Skåne', 'Vitaby'),
	(1732, 'Skåne', 'Västra Sallerup', 'Skåne', 'Eslöv'),
	(1733, 'Skåne', 'Åstorp', 'Skåne', 'Björnekulla'),
	(1734, 'Skåne', 'Åsum', '', ''),
	(1735, 'Skåne', 'Övertorneå', '', ''),
	(1736, 'Småland', 'Alvesta', 'Småland', 'Aringsås'),
	(1737, 'Småland', 'Emmaboda', 'Småland', 'Vissefjärda'),
	(1738, 'Småland', 'Gislaved', 'Småland', 'Båraryd'),
	(1739, 'Småland', 'Hallingsberg', 'Småland', 'Hallingeberg'),
	(1740, 'Småland', 'Hemmesjö med Tegnaby', 'Småland', 'Hemmesjö'),
	(1741, 'Småland', 'Hjärtlanda', 'Småland', 'Sävsjö'),
	(1742, 'Småland', 'Hultsfred', 'Småland', 'Vena'),
	(1743, 'Småland', 'Jönköping / Ljungarum', 'Småland', 'Jönköping'),
	(1744, 'Småland', 'Lessebo', 'Småland', 'Hovmantorp'),
	(1745, 'Småland', 'Ljungarum', 'Småland', 'Jönköping'),
	(1746, 'Småland', 'Ljungby', '', ''),
	(1747, 'Småland', 'Ljungby, Västra', 'Småland', 'Ljungby [Ljungby kommun]'),
	(1748, 'Småland', 'Ljungby, Östra', 'Småland', 'Ljungby [Kalmar kommun]'),
	(1749, 'Småland', 'Ljungby-G', 'Småland', 'Ljungby [Ljungby kommun]'),
	(1750, 'Småland', 'Ljungby-H', 'Småland', 'Ljungby [Kalmar kommun]'),
	(1751, 'Småland', 'Lockne', 'Småland', 'Locknevi'),
	(1752, 'Småland', 'Målilla med Gårdveda', 'Småland', 'Målilla'),
	(1753, 'Småland', 'Norra Ljunga', 'Småland', 'Sävsjö'),
	(1754, 'Småland', 'Rydaholms', 'Småland', 'Rydaholm'),
	(1755, 'Småland', 'Ryssby', '', ''),
	(1756, 'Småland', 'Ryssby Västra', 'Småland', 'Ryssby [Ljungby kommun]'),
	(1757, 'Småland', 'Ryssby Östra', 'Småland', 'Ryssby [Kalmar kommun]'),
	(1758, 'Småland', 'Ryssby, Västra', 'Småland', 'Ryssby [Ljungby kommun]'),
	(1759, 'Småland', 'Ryssby, Östra', 'Småland', 'Ryssby [Kalmar kommun]'),
	(1760, 'Småland', 'Ryssby-G', 'Småland', 'Ryssby [Ljungby kommun]'),
	(1761, 'Småland', 'Ryssby-H', 'Småland', 'Ryssby [Kalmar kommun]'),
	(1762, 'Småland', 'S. Sandsjö', 'Småland', 'Södra Sandsjö'),
	(1763, 'Småland', 'Sandseryd', 'Småland', 'Norrahammar'),
	(1764, 'Småland', 'Skillingaryd', 'Småland', 'Tofteryd'),
	(1765, 'Småland', 'Skånes-Fagerhult', '', ''),
	(1766, 'Småland', 'Svennarum', 'Småland', 'Svenarum'),
	(1767, 'Småland', 'Säve', '', ''),
	(1768, 'Småland', 'Visingsborg', 'Småland', 'Visingsö'),
	(1769, 'Småland', 'Voxtorp', '', ''),
	(1770, 'Småland', 'Voxtorp Västra', 'Småland', 'Voxtorp [Värnamo kommun]'),
	(1771, 'Småland', 'Voxtorp Östra', 'Småland', 'Voxtorp [Kalmar kommun]'),
	(1772, 'Småland', 'Voxtorp, Västra', 'Småland', 'Voxtorp [Värnamo kommun]'),
	(1773, 'Småland', 'Voxtorp, Östra', 'Småland', 'Voxtorp [Kalmar kommun]'),
	(1774, 'Småland', 'Voxtorp-F', 'Småland', 'Voxtorp [Värnamo kommun]'),
	(1775, 'Småland', 'Voxtorp-H', 'Småland', 'Voxtorp [Kalmar kommun]'),
	(1776, 'Småland', 'Voxtorps', '', ''),
	(1777, 'Småland', 'Älmhult', 'Småland', 'Stenbrohult'),
	(1778, 'Södermanland', 'Allhelgona', 'Södermanland', 'Helgona'),
	(1779, 'Södermanland', 'Boo', '', ''),
	(1780, 'Södermanland', 'Brännkyrka', 'Södermanland', 'Stockholm'),
	(1781, 'Södermanland', 'Dillnäs', 'Södermanland', 'Gåsinge-Dillnäs'),
	(1782, 'Södermanland', 'Enhörna', '', ''),
	(1783, 'Södermanland', 'Enskede', 'Södermanland', 'Stockholm'),
	(1784, 'Södermanland', 'Eskilstuna, Kloster', 'Södermanland', 'Eskilstuna'),
	(1785, 'Södermanland', 'Eslöv', '', ''),
	(1786, 'Södermanland', 'Farsta', 'Södermanland', 'Stockholm'),
	(1787, 'Södermanland', 'Flemingsberg', 'Södermanland', 'Huddinge'),
	(1788, 'Södermanland', 'Fors', '', ''),
	(1789, 'Södermanland', 'Frustuna - Kattnäs', '', ''),
	(1790, 'Södermanland', 'Frustuna/Kattnäs', '', ''),
	(1791, 'Södermanland', 'Frustuna-Kattnäs', '', ''),
	(1792, 'Södermanland', 'Gränna', '', ''),
	(1793, 'Södermanland', 'Gåsinge', 'Södermanland', 'Gåsinge-Dillnäs'),
	(1794, 'Södermanland', 'Hagby', '', ''),
	(1795, 'Södermanland', 'Hägersten', 'Södermanland', 'Stockholm'),
	(1796, 'Södermanland', 'Hällby', 'Södermanland', 'Torshälla'),
	(1797, 'Södermanland', 'Ludgo-Spelvik', '', ''),
	(1798, 'Södermanland', 'Nicolai', 'Södermanland', 'Nyköping'),
	(1799, 'Södermanland', 'Nikolai', 'Södermanland', 'Nyköping'),
	(1800, 'Södermanland', 'Saltsjöbaden', 'Södermanland', 'Nacka'),
	(1801, 'Södermanland', 'Sanct Nicolai', 'Södermanland', 'Nyköping'),
	(1802, 'Södermanland', 'Sankt Mikael', 'Södermanland', 'Huddinge'),
	(1803, 'Södermanland', 'Sankt Nicolai', 'Södermanland', 'Nyköping'),
	(1804, 'Södermanland', 'Skaftö', '', ''),
	(1805, 'Södermanland', 'Skarpnäck', 'Södermanland', 'Stockholm'),
	(1806, 'Södermanland', 'Skärholmen', 'Södermanland', 'Stockholm'),
	(1807, 'Södermanland', 'Södertölje', 'Södermanland', 'Södertälje'),
	(1808, 'Södermanland', 'Tosterö', '', ''),
	(1809, 'Södermanland', 'Trosa', 'Södermanland', 'Trosa stad'),
	(1810, 'Södermanland', 'Trosa landsförsamling', 'Södermanland', 'Trosa-Vagnhärad'),
	(1811, 'Södermanland', 'Trosa stadsförsamling', 'Södermanland', 'Trosa stad'),
	(1812, 'Södermanland', 'Trosarad', '', ''),
	(1813, 'Södermanland', 'Trångsund', '', ''),
	(1814, 'Södermanland', 'Tullinge', 'Södermanland', 'Botkyrka'),
	(1815, 'Södermanland', 'Tumba', 'Södermanland', 'Botkyrka'),
	(1816, 'Södermanland', 'Turinge', '', ''),
	(1817, 'Södermanland', 'Uppsala', '', ''),
	(1818, 'Södermanland', 'Vagnhärad', 'Södermanland', 'Trosa-Vagnhärad'),
	(1819, 'Södermanland', 'Vantör', 'Södermanland', 'Stockholm'),
	(1820, 'Södermanland', 'Vingåker', '', ''),
	(1821, 'Södermanland', 'Västertälje', 'Södermanland', 'Södertälje'),
	(1822, 'Södermanland', 'Östergarn', '', ''),
	(1823, 'Södermanland', 'Överum', '', ''),
	(1824, 'Torne lappmark', 'Jokkmokk', '', ''),
	(1825, 'Torne lappmark', 'Jukkasjävi', 'Torne lappmark', 'Jukkasjärvi'),
	(1826, 'Torne lappmark', 'Kiruna', 'Torne lappmark', 'Jukkasjärvi'),
	(1827, 'Torne lappmark', 'Uddevalla', '', ''),
	(1828, 'Torne lappmark', 'Vittangi', 'Torne lappmark', 'Jukkasjärvi'),
	(1829, 'Uppland', 'Barkarby', 'Uppland', 'Järfälla'),
	(1830, 'Uppland', 'Bergshamra', '', ''),
	(1831, 'Uppland', 'Björkö', 'Uppland', 'Björkö-Arholma'),
	(1832, 'Uppland', 'Bo', 'Uppland', 'Boo'),
	(1833, 'Uppland', 'Bondkyrka', 'Uppland', 'Uppsala'),
	(1834, 'Uppland', 'Bromma', 'Uppland', 'Stockholm'),
	(1835, 'Uppland', 'Färingsö', 'Uppland', 'Sånga'),
	(1836, 'Uppland', 'Gamla Uppsala', 'Uppland', 'Uppsala'),
	(1837, 'Uppland', 'Gottsunda', 'Uppland', 'Uppsala'),
	(1838, 'Uppland', 'Hammarö', '', ''),
	(1839, 'Uppland', 'Heliga Trefaldighet', 'Uppland', 'Uppsala'),
	(1840, 'Uppland', 'Husby-Lyhundra', '', ''),
	(1841, 'Uppland', 'Husby-Ärlighundra', 'Uppland', 'Husby-Ärlinghundra'),
	(1842, 'Uppland', 'Hässelby', 'Uppland', 'Stockholm'),
	(1843, 'Uppland', 'Jakobsberg', 'Uppland', 'Järfälla'),
	(1844, 'Uppland', 'Kallhäll', 'Uppland', 'Järfälla'),
	(1845, 'Uppland', 'Kista', 'Uppland', 'Stockholm'),
	(1846, 'Uppland', 'Kristianstad', '', ''),
	(1847, 'Uppland', 'Ljusterö-Kulla', 'Uppland', 'Ljusterö'),
	(1848, 'Uppland', 'Nysund', '', ''),
	(1849, 'Uppland', 'Nämdö', '', ''),
	(1850, 'Uppland', 'Ornö', '', ''),
	(1851, 'Uppland', 'Roslagskulla', 'Uppland', 'Roslags-Kulla'),
	(1852, 'Uppland', 'Råsunda', 'Uppland', 'Solna'),
	(1853, 'Uppland', 'S:t Olof', 'Uppland', 'Sigtuna'),
	(1854, 'Uppland', 'S:t Per', 'Uppland', 'Sigtuna'),
	(1855, 'Uppland', 'Sankt Olof', 'Uppland', 'Sigtuna'),
	(1856, 'Uppland', 'Sankt Per', 'Uppland', 'Sigtuna'),
	(1857, 'Uppland', 'Skutskär', 'Uppland', 'Älvkarleby'),
	(1858, 'Uppland', 'Spånga', 'Uppland', 'Stockholm'),
	(1859, 'Uppland', 'Stockholm, Bromma', 'Uppland', 'Stockholm'),
	(1860, 'Uppland', 'Stockholms-Näs', 'Uppland', 'Kungsängen'),
	(1861, 'Uppland', 'Stockhom', 'Uppland', 'Stockholm'),
	(1862, 'Uppland', 'Stoclholm', 'Uppland', 'Stockholm'),
	(1863, 'Uppland', 'Sunne', '', ''),
	(1864, 'Uppland', 'Svinngarn', 'Uppland', 'Svinnegarn'),
	(1865, 'Uppland', 'Söderby Karl', 'Uppland', 'Söderby-Karl'),
	(1866, 'Uppland', 'Tibble', '', ''),
	(1867, 'Uppland', 'Valsta', 'Uppland', 'Husby-Ärlinghundra'),
	(1868, 'Uppland', 'Viksjö', 'Uppland', 'Järfälla'),
	(1869, 'Uppland', 'Vällingby', 'Uppland', 'Stockholm'),
	(1870, 'Uppland', 'Västerled', 'Uppland', 'Stockholm'),
	(1871, 'Uppland', 'Ö. Ryd', 'Uppland', 'Östra Ryd'),
	(1872, 'Uppland', 'Örbyhus', '', ''),
	(1873, 'Uppland', 'Össebygran', 'Uppland', 'Össeby-Garn'),
	(1874, 'Uppland', 'Österåker-Östra Ryd', '', ''),
	(1875, 'Uppland', 'Övergran Tensta', '', ''),
	(1876, 'Värmland', 'By', 'Värmland', 'Säffle'),
	(1877, 'Värmland', 'Deje', '', ''),
	(1878, 'Värmland', 'Göteborg', '', ''),
	(1879, 'Värmland', 'Karlstads domkyrkoförsamling', 'Värmland', 'Karlstad'),
	(1880, 'Värmland', 'Karvia', '', ''),
	(1881, 'Värmland', 'Mjusjön', '', ''),
	(1882, 'Värmland', 'Molkom', '', ''),
	(1883, 'Värmland', 'Munkfors', 'Värmland', 'Ransäter'),
	(1884, 'Värmland', 'N. Finnskoga', 'Värmland', 'Norra Finnskoga'),
	(1885, 'Värmland', 'Norra Ullerud', '', ''),
	(1886, 'Värmland', 'Ny-Huggenäs', '', ''),
	(1887, 'Värmland', 'Storfors', 'Värmland', 'Kroppa'),
	(1888, 'Värmland', 'Tveta', 'Värmland', 'Säffle'),
	(1889, 'Värmland', 'Vanum', 'Värmland', 'Kristinehamn'),
	(1890, 'Värmland', 'Varnum', '', ''),
	(1891, 'Värmland', 'Väsa', 'Värmland', 'Väse'),
	(1892, 'Västerbotten', 'Boliden', 'Västerbotten', 'Skellefteå'),
	(1893, 'Västerbotten', 'Dorotea', '', ''),
	(1894, 'Västerbotten', 'Fällfors', 'Västerbotten', 'Byske'),
	(1895, 'Västerbotten', 'Holmsund', 'Västerbotten', 'Umeå'),
	(1896, 'Västerbotten', 'Kalvträsk', 'Västerbotten', 'Burträsk'),
	(1897, 'Västerbotten', 'Kågedalen', 'Västerbotten', 'Skellefteå'),
	(1898, 'Västerbotten', 'Nederluleå', '', ''),
	(1899, 'Västerbotten', 'Sankt Örjan', 'Västerbotten', 'Skellefteå'),
	(1900, 'Västerbotten', 'Skelleft3å', 'Västerbotten', 'Skellefteå'),
	(1901, 'Västerbotten', 'Skellefte', 'Västerbotten', 'Skellefteå'),
	(1902, 'Västerbotten', 'Skellefteå landsförsamling', 'Västerbotten', 'Skellefteå'),
	(1903, 'Västerbotten', 'Teg', 'Västerbotten', 'Umeå'),
	(1904, 'Västerbotten', 'Ume', 'Västerbotten', 'Umeå'),
	(1905, 'Västerbotten', 'Vilhelmina', '', ''),
	(1906, 'Västerbotten', 'Vindeln', 'Västerbotten', 'Degerfors'),
	(1907, 'Västerbotten', 'Åmsele', 'Västerbotten', 'Degerfors'),
	(1908, 'Västerbotten', 'Överluleå', '', ''),
	(1909, 'Västergötland', 'Ale- Skövde', 'Västergötland', 'Ale-Skövde'),
	(1910, 'Västergötland', 'Bitterna', 'Västergötland', ''),
	(1911, 'Västergötland', 'Brunn', 'Västergötland', 'Ulricehamn'),
	(1912, 'Västergötland', 'Dimbo-Ottravad', '', ''),
	(1913, 'Västergötland', 'Eggby-Istrum', '', ''),
	(1914, 'Västergötland', 'Freiggeråker', 'Västergötland', 'Friggeråker'),
	(1915, 'Västergötland', 'Friggesåker', 'Västergötland', 'Friggeråker'),
	(1916, 'Västergötland', 'Fristad-Gingri', '', ''),
	(1917, 'Västergötland', 'Fässbeg', 'Västergötland', 'Mölndal'),
	(1918, 'Västergötland', 'Gunnared', 'Västergötland', 'Angered'),
	(1919, 'Västergötland', 'Gustav-Adolf', 'Västergötland', 'Gustav Adolf'),
	(1920, 'Västergötland', 'Göteborg / Lundby', 'Västergötland', 'Göteborg'),
	(1921, 'Västergötland', 'Kattunga', '', ''),
	(1922, 'Västergötland', 'Lena-Bergstena', '', ''),
	(1923, 'Västergötland', 'Ljunghems', 'Västergötland', 'Ljunghem'),
	(1924, 'Västergötland', 'Lundby', 'Västergötland', 'Göteborg'),
	(1925, 'Västergötland', 'Lundby / Tuve', '', ''),
	(1926, 'Västergötland', 'Lundby/Tuve', '', ''),
	(1927, 'Västergötland', 'Norra Råda', '', ''),
	(1928, 'Västergötland', 'Råda', '', ''),
	(1929, 'Västergötland', 'Råda, Kållands-', 'Västergötland', 'Råda [Lidköpings kommun]'),
	(1930, 'Västergötland', 'Råda-O', 'Västergötland', 'Råda [Härryda kommun]'),
	(1931, 'Västergötland', 'S:t Peder', 'Västergötland', 'Sankt Peder'),
	(1932, 'Västergötland', 'Sankt Anna', '', ''),
	(1933, 'Västergötland', 'Sankt Peter', 'Västergötland', 'Sankt Peder'),
	(1934, 'Västergötland', 'Sjogerstad-Rådene', '', ''),
	(1935, 'Västergötland', 'Stensjön', 'Västergötland', 'Mölndal'),
	(1936, 'Västergötland', 'Surteby', 'Västergötland', 'Surteby-Kattunga'),
	(1937, 'Västergötland', 'Svenljunga-Ullasjö', '', ''),
	(1938, 'Västergötland', 'Sävar', '', ''),
	(1939, 'Västergötland', 'Sävedalen', 'Västergötland', 'Partille'),
	(1940, 'Västergötland', 'Ugglums', 'Västergötland', 'Ugglum'),
	(1941, 'Västergötland', 'Ulricehamns', 'Västergötland', 'Ulricehamn'),
	(1942, 'Västergötland', 'Uppsala', '', ''),
	(1943, 'Västergötland', 'Vassända-Naglum', '', ''),
	(1944, 'Västergötland', 'Vilske', '', ''),
	(1945, 'Västergötland', 'Vist', 'Västergötland', 'Ulricehamn'),
	(1946, 'Västergötland', 'Vänersbotg', 'Västergötland', 'Vänersborg'),
	(1947, 'Västergötland', 'Västra Frölunda', 'Västergötland', 'Göteborg'),
	(1948, 'Västergötland', 'Åsarp', '', ''),
	(1949, 'Västergötland', 'Åsarp-Smula', '', ''),
	(1950, 'Västergötland', 'Älvsborg', 'Västergötland', 'Göteborg'),
	(1951, 'Västergötland', 'Örgryte', 'Västergötland', 'Göteborg'),
	(1952, 'Västergötland', 'ÖrslösaKällstorp', '', ''),
	(1953, 'Västmanland', 'Badelunda', 'Västmanland', 'Västerås'),
	(1954, 'Västmanland', 'Bro', 'Västmanland', 'Kolsva'),
	(1955, 'Västmanland', 'Guldsmedshyttan', 'Västmanland', 'Linde'),
	(1956, 'Västmanland', 'Hallstahammar', 'Västmanland', 'Svedvi'),
	(1957, 'Västmanland', 'Halstahammar', 'Västmanland', 'Svedvi'),
	(1958, 'Västmanland', 'Huddunge', '', ''),
	(1959, 'Västmanland', 'Hudiksvall', '', ''),
	(1960, 'Västmanland', 'Kungsör', '', ''),
	(1961, 'Västmanland', 'Lerbäck', '', ''),
	(1962, 'Västmanland', 'Lundby', 'Västmanland', 'Västerås'),
	(1963, 'Västmanland', 'Malma', 'Västmanland', 'Kolsva'),
	(1964, 'Västmanland', 'Nora bergsförsamling', 'Västmanland', 'Nora'),
	(1965, 'Västmanland', 'Norsjö', '', ''),
	(1966, 'Västmanland', 'S:t Ilian', 'Västmanland', 'Västerås'),
	(1967, 'Västmanland', 'Skerike', 'Västmanland', 'Västerås'),
	(1968, 'Västmanland', 'Storå', '', ''),
	(1969, 'Västmanland', 'Surahammar', 'Västmanland', 'Sura'),
	(1970, 'Västmanland', 'Säterbo', 'Västmanland', 'Arboga'),
	(1971, 'Västmanland', 'Västanfors', 'Västmanland', 'Fagersta'),
	(1972, 'Västmanland', 'Väster-Färnebo', 'Västmanland', 'Västerfärnebo'),
	(1973, 'Västmanland', 'Ånimskog', '', ''),
	(1974, 'Västmanland', 'Östmark', '', ''),
	(1975, 'Ångermanland', 'Frånö', '', ''),
	(1976, 'Ångermanland', 'Gudmundrå', 'Ångermanland', 'Kramfors'),
	(1977, 'Ångermanland', 'Hernösand', 'Ångermanland', 'Härnösand'),
	(1978, 'Ångermanland', 'Hoting', '', ''),
	(1979, 'Ångermanland', 'Härnö', 'Ångermanland', 'Härnösand'),
	(1980, 'Ångermanland', 'Härnön', 'Ångermanland', 'Härnösand'),
	(1981, 'Ångermanland', 'Multrå', 'Ångermanland', 'Sollefteå'),
	(1982, 'Ångermanland', 'Revsund', '', ''),
	(1983, 'Ångermanland', 'Solleftå', 'Ångermanland', 'Sollefteå'),
	(1984, 'Ångermanland', 'Säbro', 'Ångermanland', 'Säbrå'),
	(1985, 'Ångermanland', 'Torp', '', ''),
	(1986, 'Ångermanland', 'Undersåker', '', ''),
	(1987, 'Ångermanland', 'Vänersbotg', '', ''),
	(1988, 'Ångermanland', 'Ådalsliden', 'Ångermanland', 'Ådals-Liden'),
	(1989, 'Åsele lappmark', 'Arvidsjaur', '', ''),
	(1990, 'Åsele lappmark', 'Risbäck', 'Åsele lappmark', 'Dorotea'),
	(1991, 'Åsele lappmark', 'Tärna', '', ''),
	(1992, 'Åsele lappmark', 'Undersåker', '', ''),
	(1993, 'Öland', 'Bredsätra', 'Öland', 'Bredsättra'),
	(1994, 'Öland', 'Byerum', '', ''),
	(1995, 'Öland', 'Ekby', 'Öland', 'Egby'),
	(1996, 'Öland', 'Kalkstad', '', ''),
	(1997, 'Öland', 'Misterhult', '', ''),
	(1998, 'Öland', 'Repplinge', 'Öland', 'Räpplinge'),
	(1999, 'Öland', 'Stenninge', '', ''),
	(2000, 'Öland', 'Tveta', 'Öland', 'Torslunda'),
	(2001, 'Östergötland', 'Björksta', '', ''),
	(2002, 'Östergötland', 'Borg', 'Östergötland', 'Norrköping'),
	(2003, 'Östergötland', 'Borgholm', '', ''),
	(2004, 'Östergötland', 'Dorotea', '', ''),
	(2005, 'Östergötland', 'Kullerstads', 'Östergötland', 'Kullerstad'),
	(2006, 'Östergötland', 'Kville', '', ''),
	(2007, 'Östergötland', 'Lummelunda', '', ''),
	(2008, 'Östergötland', 'Medelplana', '', ''),
	(2009, 'Östergötland', 'Muskö', '', ''),
	(2010, 'Östergötland', 'S:t Anna', 'Östergötland', 'Sankt Anna'),
	(2011, 'Östergötland', 'S:t Johannes', 'Östergötland', 'Norrköping'),
	(2012, 'Östergötland', 'Sankt Johannes', 'Östergötland', 'Norrköping'),
	(2013, 'Östergötland', 'Sankt Lars', 'Östergötland', 'Linköping'),
	(2014, 'Östergötland', 'Styrestad', 'Östergötland', 'Styrstad'),
	(2015, 'Östergötland', 'Södra Fågelås', '', ''),
	(2016, 'Östergötland', 'Tammela', '', ''),
	(2017, 'Östergötland', 'Valdemarsvik', 'Östergötland', 'Ringarum'),
	(2018, 'Östergötland', 'Varv och Styra', '', ''),
	(2019, 'Östergötland', 'Vinnerstad', 'Östergötland', 'Motala'),
	(2020, 'Östergötland', 'Vreta', 'Östergötland', 'Vreta Kloster'),
	(2021, 'Östergötland', 'Ydre', '', ''),
	(2022, 'Östergötland', 'Åtvidaberg', 'Östergötland', 'Åtvid'),
	(2023, 'Östergötland', 'Österåker-Östra Ryd', '', ''),
	(2024, 'Östergötland', 'Östra Eneby', 'Östergötland', 'Norrköping');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
