-- --------------------------------------------------------
-- Host:                         172.18.144.38
-- Server version:               8.0.31 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.4.0.6659
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table samhall.fix_country
CREATE TABLE IF NOT EXISTS `fix_country` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `ContinentS` enum('','Africa','Antarctica','Asia','Australia & Oceania','Europe','North America','Oceania','South & Central America','South America','Austrailia') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '' COMMENT 'Wrong continent + Country that should be automatically corrected',
  `CountryS` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '' COMMENT 'Wrong continent + Country  that should be automatically corrected',
  `Continent` enum('','Africa','Antarctica','Asia','Australia & Oceania','Europe','North America','Oceania','South & Central America','South America','Austrailia') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '' COMMENT 'correct Continent',
  `Country` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '' COMMENT 'correct Country',
  `coments` text,
  PRIMARY KEY (`id`),
  KEY `ContinentS` (`ContinentS`),
  KEY `CountryS` (`CountryS`)
) ENGINE=InnoDB AUTO_INCREMENT=150 DEFAULT CHARSET=utf8mb3 COMMENT='a table for automaticaly change country names when importing data to the db';

-- Dumping data for table samhall.fix_country: ~127 rows (approximately)
INSERT INTO `fix_country` (`id`, `ContinentS`, `CountryS`, `Continent`, `Country`, `coments`) VALUES
	(2, 'Africa', 'Côte D’Ivoire', 'Africa', 'Côte d\'Ivoire', NULL),
	(3, 'Antarctica', 'French Southern Territories', 'Africa', 'French Southern Territories', 'UPS'),
	(4, 'Africa', 'Libyan Arab Jamahiriya', 'Africa', 'Libya', 'S, förkortar namn'),
	(6, 'Africa', 'Tanzania, United republic of', 'Africa', 'Tanzania', 'S, förkortar namn'),
	(7, 'Africa', 'unknown country', 'Africa', '', 'S'),
	(8, 'Asia', 'Brunei Darussalam', 'Asia', 'Brunei', 'S, förkortar namn'),
	(9, 'Asia', 'Iran, Islamic republic of', 'Asia', 'Iran', 'S, förkortar namn'),
	(10, 'Asia', 'Korea, Democratic people’s republic of', 'Asia', 'North Korea', 'S, förkortar namn'),
	(11, 'Asia', 'Korea, Republic of', 'Asia', 'South Korea', 'S, förkortar namn'),
	(12, 'Asia', 'Lao people’s democratic republic', 'Asia', 'Laos', 'S, förkortar namn'),
	(13, 'Asia', 'Russian Federation', 'Asia', 'Russia', 'S GB, förkortar namn'),
	(14, 'Asia', 'Syrian arab republic', 'Asia', 'Syria', 'S, förkortar namn'),
	(15, 'Asia', 'Taiwan, Province of China', 'Asia', 'Taiwan', 'S, förkortar namn'),
	(16, 'Asia', 'unknown country', 'Asia', '', 'S'),
	(17, 'Asia', 'Viet Nam', 'Asia', 'Vietnam', NULL),
	(18, 'Europe', 'Austria / Switzerland', 'Europe', '', NULL),
	(19, 'Europe', 'Denmark / Sweden', 'Europe', '', NULL),
	(20, 'Europe', 'Macedonia, The Former Yugoslav Republic of', 'Europe', 'North Macedonia', ', förkortar namn'),
	(21, 'Europe', 'Norway / Sweden', 'Europe', '', NULL),
	(22, 'Europe', 'Russian Federation', 'Europe', 'Russia', ', förkortar namn'),
	(24, 'North America', 'Honduras', 'South & Central America', 'Honduras', 'byter Världsdel'),
	(25, 'South America', 'Bermuda', 'North America', 'Bermuda', 'byter Världsdel'),
	(26, 'North America', 'Bahamas', 'South & Central America', 'Bahamas', 'byter Världsdel'),
	(27, 'North America', 'Belize', 'South & Central America', 'Belize', 'byter Världsdel'),
	(28, 'North America', 'Costa Rica', 'South & Central America', 'Costa Rica', 'byter Världsdel'),
	(29, 'North America', 'Cuba', 'South & Central America', 'Cuba', 'byter Världsdel'),
	(30, 'North America', 'Dominica', 'South & Central America', 'Dominica', 'byter Världsdel'),
	(31, 'North America', 'Dominican Republic', 'South & Central America', 'Dominican Republic', 'byter Världsdel'),
	(32, 'North America', 'El Salvador', 'South & Central America', 'El Salvador', 'byter Världsdel'),
	(33, 'North America', 'Grenada', 'South & Central America', 'Grenada', 'byter Världsdel'),
	(34, 'North America', 'Guatemala', 'South & Central America', 'Guatemala', 'byter Världsdel'),
	(35, 'North America', 'Haiti', 'South & Central America', 'Haiti', 'byter Världsdel'),
	(36, 'North America', 'Jamaica', 'South & Central America', 'Jamaica', 'byter Världsdel'),
	(37, 'North America', 'Nicaragua', 'South & Central America', 'Nicaragua', 'byter Världsdel'),
	(38, 'North America', 'Panama', 'South & Central America', 'Panama', 'byter Världsdel'),
	(39, 'South America', 'Saint Kitts and Nevis', 'South & Central America', 'Saint Kitts and Nevis', 'byter Världsdel'),
	(40, 'North America', 'Saint Lucia', 'South & Central America', 'Saint Lucia', 'byter Världsdel'),
	(41, 'South America', 'Saint Vincent and the Grenadines', 'South & Central America', 'Saint Vincent and the Grenadines', 'byter Världsdel'),
	(44, 'Asia', 'Solomon Islands', 'Oceania', 'Solomon Islands', 'byter Världsdel'),
	(45, 'Europe', 'Cyprus', 'Asia', 'Cyprus', 'byter Världsdel'),
	(46, 'Europe', 'Greenland', 'North America', 'Greenland', 'byter Världsdel'),
	(49, 'North America', 'Saint Kitts And Nevis', 'South & Central America', 'Saint Kitts and Nevis', NULL),
	(50, 'North America', 'Saint Pierre And Miquelon', 'North America', 'Saint Pierre and Miquelon', NULL),
	(51, 'North America', 'Saint Vincent And The Grenadines', 'South & Central America', 'Saint Vincent and the Grenadines', NULL),
	(52, 'North America', 'Trinidad and Tobago', 'South & Central America', 'Trinidad and Tobago', NULL),
	(53, 'Oceania', 'Cocos (Keeling) Islands', 'Asia', 'Cocos (Keeling) Islands', NULL),
	(55, 'North America', 'Guadeloupe', 'South & Central America', 'Guadeloupe', NULL),
	(56, 'North America', 'Martinique', 'South & Central America', 'Martinique', NULL),
	(57, 'North America', 'Puerto Rico', 'South & Central America', 'Puerto Rico', NULL),
	(60, 'North America', 'Virgin Islands, U. S.', 'South & Central America', 'Virgin Islands, U.S.', NULL),
	(61, 'Africa', 'Congo, The Democratic Republic Of The', 'Africa', 'Congo, The Democratic Republic of the', NULL),
	(62, 'South America', 'unknown country', 'South & Central America', '', 'S'),
	(63, 'South America', 'Falkland Islands (Malvinas)', 'South & Central America', 'Falkland Islands ', NULL),
	(65, 'North America', 'Antigua and Barbuda', 'South & Central America', 'Antigua and Barbuda', NULL),
	(66, 'North America', 'Barbados', 'South & Central America', 'Barbados', NULL),
	(67, 'North America', 'Cayman Islands', 'South & Central America', 'Cayman Islands', NULL),
	(68, 'North America', 'Montserrat', 'South & Central America', 'Montserrat', NULL),
	(69, 'South America', 'Saint Vincent and the Grenedines', 'South & Central America', 'Saint Vincent and the Grenadines', NULL),
	(70, 'North America', 'Virgin Islands, British', 'South & Central America', 'Virgin Islands, British', NULL),
	(72, 'South America', 'Brazil', 'South & Central America', 'Brazil', NULL),
	(73, 'South America', 'Colombia', 'South & Central America', 'Colombia', NULL),
	(74, 'South America', 'Argentina', 'South & Central America', 'Argentina', NULL),
	(75, 'South America', 'Peru', 'South & Central America', 'Peru', NULL),
	(76, 'South America', 'Venezuela', 'South & Central America', 'Venezuela', NULL),
	(77, 'South America', 'Chile', 'South & Central America', 'Chile', NULL),
	(78, 'South America', 'Ecuador', 'South & Central America', 'Ecuador', NULL),
	(79, 'South America', 'Bolivia', 'South & Central America', 'Bolivia', NULL),
	(80, 'South America', 'Paraguay', 'South & Central America', 'Paraguay', NULL),
	(81, 'South America', 'Uruguay', 'South & Central America', 'Uruguay', NULL),
	(82, 'South America', 'Guyana', 'South & Central America', 'Guyana', NULL),
	(83, 'South America', 'Suriname', 'South & Central America', 'Suriname', NULL),
	(84, 'South America', 'French Guiana', 'South & Central America', 'French Guiana', NULL),
	(85, 'South America', 'Falkland Islands (UK)', 'South & Central America', 'Falkland Islands', NULL),
	(86, 'South America', '', 'South & Central America', '', NULL),
	(87, 'South America', '', 'South & Central America', '', NULL),
	(88, 'South America', 'Anguilla', 'South & Central America', 'Anguilla', NULL),
	(91, 'South America', 'Curacao', 'South & Central America', 'Curaçao', NULL),
	(92, 'South America', 'Falkland Islands', 'South & Central America', 'Falkland Islands', NULL),
	(94, 'South America', 'South Georgia and the South Sandwich Islands', 'South & Central America', 'South Georgia and the South Sandwich Islands', NULL),
	(95, 'South America', 'Trinidad and Tobago', 'South & Central America', 'Trinidad and Tobago', NULL),
	(96, 'South America', 'Virgin Islands, U.S.', 'South & Central America', 'Virgin Islands, U.S.', NULL),
	(97, 'North America', 'Saint Vincent And The Grenedines', 'South & Central America', 'Saint Vincent and the Grenadines', NULL),
	(99, 'North America', 'Virgin Islands, U.S.', 'South & Central America', 'Virgin Islands, U.S.', NULL),
	(100, 'Australia & Oceania', '', 'Oceania', '', NULL),
	(101, 'Australia & Oceania', '', 'Oceania', '', NULL),
	(102, 'Australia & Oceania', 'Australia', 'Oceania', 'Australia', NULL),
	(103, 'Australia & Oceania', 'New Zealand', 'Oceania', 'New Zealand', NULL),
	(104, 'Australia & Oceania', 'New Zeeland', 'Oceania', 'New Zealand', NULL),
	(105, 'Australia & Oceania', 'United States', 'Oceania', 'United States', NULL),
	(106, 'South America', 'Belize', 'South & Central America', 'Belize', NULL),
	(107, 'South America', 'Costa Rica', 'South & Central America', 'Costa Rica', NULL),
	(108, 'South America', 'Cuba', 'South & Central America', 'Cuba', NULL),
	(109, 'South America', 'Dominica', 'South & Central America', 'Dominica', NULL),
	(110, 'South America', 'Dominican Republic', 'South & Central America', 'Dominican Republic', NULL),
	(111, 'South America', 'Grenada', 'South & Central America', 'Grenada', NULL),
	(112, 'South America', 'Jamaica', 'South & Central America', 'Jamaica', NULL),
	(113, 'South America', 'Martinique', 'South & Central America', 'Martinique', NULL),
	(114, 'South America', 'Panama', 'South & Central America', 'Panama', NULL),
	(115, 'South America', 'Puerto Rico', 'South & Central America', 'Puerto Rico', NULL),
	(116, 'Australia & Oceania', 'French Polynesia', 'Oceania', 'French Polynesia', NULL),
	(117, 'South America', 'Antarctica', 'Antarctica', 'Antarctica', NULL),
	(118, 'South America', 'Antigua and Barbuda', 'South & Central America', 'Antigua and Barbuda', NULL),
	(119, 'South America', 'Bahamas', 'South & Central America', 'Bahamas', NULL),
	(120, 'South America', 'El Salvador', 'South & Central America', 'El Salvador', NULL),
	(121, 'South America', 'Guadeloupe', 'South & Central America', 'Guadeloupe', NULL),
	(122, 'South America', 'Guatemala', 'South & Central America', 'Guatemala', NULL),
	(123, 'South America', 'Haiti', 'South & Central America', 'Haiti', NULL),
	(124, 'South America', 'Honduras', 'South & Central America', 'Honduras', NULL),
	(125, 'South America', 'Nicaragua', 'South & Central America', 'Nicaragua', NULL),
	(128, 'South America', 'Saint Lucia', 'South & Central America', 'Saint Lucia', NULL),
	(130, 'Europe', 'Moldova, Republic of', 'Europe', 'Moldova', 'S'),
	(131, 'Europe', 'unknown country', 'South & Central America', '', 'S'),
	(133, 'Africa', 'French southern territories', 'Africa', 'French Southern Territories', NULL),
	(134, 'Oceania', 'Papua New Guinea', 'Asia', 'Papua New Guinea', NULL),
	(136, 'Europe', 'United kingdom', 'Europe', 'United Kingdom', NULL),
	(137, 'Europe', 'Georgia', 'Asia', 'Georgia', NULL),
	(140, 'South America', 'Mexico', 'North America', 'Mexico', NULL),
	(141, 'South America', 'Reunion', 'Africa', 'Réunion', NULL),
	(142, 'Asia', 'Vietnamn', 'Asia', 'Vietnam', NULL),
	(143, 'Europe', 'Kroatia', 'Europe', 'Croatia', NULL),
	(144, 'North America', 'Colombia', 'South & Central America', 'Colombia', 'S'),
	(145, 'North America', 'Bolivia', 'South & Central America', 'Bolivia', NULL),
	(146, 'North America', 'Brazil', 'South & Central America', 'Brazil', 'S'),
	(147, 'North America', 'Svalbard and Jan Mayen', 'Europe', 'Svalbard and Jan Mayen', 'S'),
	(148, 'Oceania', 'South Georgia and the South Sandwich Islands', 'South & Central America', 'South Georgia and the South Sandwich Islands', NULL),
	(149, 'Europe', 'Macedonia', 'Europe', 'North Macedonia', 'The name of the country have stabilized to North Macedonia'),
	(150, 'Africa', 'Saint Helena', 'Africa', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena ska räknas som en provins');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
