-- --------------------------------------------------------
-- Host:                         172.18.144.38
-- Server version:               8.0.31 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.2.0.6576
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table samhall.samlare
CREATE TABLE IF NOT EXISTS `samlare` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT,
  `Fornamn` varchar(45) DEFAULT NULL,
  `Efternamn` varchar(45) DEFAULT NULL,
  `Birth` varchar(8) DEFAULT NULL,
  `death` varchar(8) DEFAULT NULL,
  `Ful_Fornamn` varchar(45) DEFAULT NULL,
  `Ful_Efternamn` varchar(45) DEFAULT NULL,
  `biografiska uppgifter` text,
  `country_born` text,
  `country_deceased` text,
  `kallor` text,
  `aktiv_start` int DEFAULT NULL,
  `aktiv_slut` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Who2` (`Ful_Fornamn`,`Ful_Efternamn`),
  KEY `Fornmamn` (`Fornamn`)
) ENGINE=InnoDB AUTO_INCREMENT=825 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT='a list of common collectors';

-- Dumping data for table samhall.samlare: ~797 rows (approximately)
INSERT INTO `samlare` (`ID`, `Fornamn`, `Efternamn`, `Birth`, `death`, `Ful_Fornamn`, `Ful_Efternamn`, `biografiska uppgifter`, `country_born`, `country_deceased`, `kallor`, `aktiv_start`, `aktiv_slut`) VALUES
	(3, 'Lars', 'Söderström', '1954', '', 'Lars Gustav', 'Söderström', 'Jobbade på umeå universitet senare i nord Norge', 'Sweden', NULL, NULL, NULL, NULL),
	(5, 'Avi Johannes', 'Huuskonen', '1902', '', 'Avi Johannes', 'Huuskonen', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 'Alarik', 'Hülphers', '1882', '1948', 'K. Alarik', 'Hülphers', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 'Carl', 'Stenholm', '1862', '1939', 'Carl', 'Stenholm', NULL, NULL, NULL, NULL, NULL, NULL),
	(8, 'Carl Axel', 'Torén', '1887', '1961', 'Carl Axel Oscar', 'Torén', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 'Per Adolf', 'Larsson', '1872', '1957', 'Per Adolf', 'Larsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 'Frans Otto', 'Westerberg', '1845', '1908', 'Frans Otto', 'Westerberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 'Oscar', 'Henriksson', '', '', 'Oscar', 'Henriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 'Tore M.', 'Norstad', '', '', 'Tore M.', 'Pettersson / Norstad', NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 'Bengt', 'Pettersson', '1915', '2002', 'Bengt', 'Pettersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 'Bengt Gunnar', 'Jonsson', '1963', '', 'Bengt Gunnar', 'Jonsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 'Alfred', 'Arvén', '1848', '1930', 'Alfred', 'Arvén', NULL, NULL, NULL, NULL, NULL, NULL),
	(16, 'Alfred Henry', 'Brinkman', '1873', '1928', 'Alfred Henry', 'Brinkman', NULL, NULL, NULL, NULL, NULL, NULL),
	(17, 'A.', 'Lawadanski', '', '', 'A.', 'Lawadanski', NULL, NULL, NULL, NULL, NULL, NULL),
	(18, 'Åke', 'Hovgard', '1896', '', 'Åke Thure', 'Hovgard / Trulsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(19, 'Björn', 'Moraeus', '', '', 'Björn', 'Moraeus', NULL, NULL, NULL, NULL, NULL, NULL),
	(20, 'Carl Albert', 'Tärnlund', '1868', '1953', 'Carl Albert', 'Tärnlund', NULL, NULL, NULL, NULL, NULL, NULL),
	(21, 'Carl', 'Hartman', '1824', '1884', 'Carl', 'Hartman', NULL, NULL, NULL, NULL, NULL, NULL),
	(22, 'C. L.', 'Löfvander', '1897', '1911', 'C. L.', 'Löfvander', NULL, NULL, NULL, NULL, NULL, NULL),
	(23, 'Carl', 'Sandberg', '1871', '1944', 'Carl', 'Sandberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(24, 'Ewald', 'Ährling', '1837', '1888', 'Ewald Johan Erik', 'Ährling', NULL, NULL, NULL, NULL, NULL, NULL),
	(25, 'Elof', 'Jäderholm', '1868', '1927', 'Elof Axel', 'Jäderholm', NULL, NULL, NULL, NULL, NULL, NULL),
	(26, 'Elsa', 'Nyholm', '1911', '2002', 'Elsa Cecilia', 'Nyholm / Tufvesson', NULL, NULL, NULL, NULL, NULL, NULL),
	(27, 'Erik', 'Evers', NULL, NULL, 'Erik', 'Evers', NULL, NULL, NULL, NULL, NULL, NULL),
	(28, 'Erik', 'Julin', '', '', 'Erik R.', 'Julin', NULL, NULL, NULL, NULL, NULL, NULL),
	(29, 'Erik', 'Nyman', '1866', '1900', 'Erik', 'Nyman', NULL, NULL, NULL, NULL, NULL, NULL),
	(30, 'Erik', 'Vrang', '1870', '1958', 'Erik Pärsson', 'Vrang', NULL, NULL, NULL, NULL, NULL, NULL),
	(31, 'Gösta Robert', 'Cedergren', '1888', '1954', 'Gösta Robert Israel ', 'Cedergren', NULL, NULL, NULL, NULL, NULL, NULL),
	(32, 'Gunnar', 'Samuelsson', '1885', '1944', 'Gunnar', 'Samuelsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(33, 'Harald E.', 'Johansson', '1880', '1931', 'Harald E.', 'Johansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(34, 'Harald', 'Lindberg', '1871', '1963', 'Harald', 'Lindberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(35, 'Hjalmar', 'Möller', '1866', '1941', 'Hjalmar August', 'Möller', NULL, NULL, NULL, NULL, NULL, NULL),
	(36, 'Ivar', 'Söderberg', '1889', '', 'Ivar', 'Söderberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(37, 'Johan Emanuel', 'Zetterstedt', '1828', '1880', 'Johan Emanuel', 'Zetterstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(38, 'Judith', 'Christoffersson', '', '', 'Judith', 'Christoffersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(39, 'Knut Fredrik', 'Thedenius', '1814', '1894', 'Knut Fredrik', 'Thedenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(40, 'Karl', 'Johansson', '1856', '1928', 'Karl', 'Johansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(41, 'Kristoffer', 'Hylander', '1970', '', 'Kristoffer', 'Hylander', NULL, NULL, NULL, NULL, NULL, NULL),
	(42, 'Lars', 'Fagerström', '', '', 'Lars', 'Fagerström', NULL, NULL, NULL, NULL, NULL, NULL),
	(43, 'Magnus', 'Huss', '1807', '1890', 'Magnus', 'Huss', NULL, NULL, NULL, NULL, NULL, NULL),
	(44, 'Matti', 'Haapasaari', '1939', '', 'Matti K.', 'Haapasaari', NULL, NULL, NULL, NULL, NULL, NULL),
	(45, 'Nils Conrad', 'Kindberg', '1832', '1910', 'Nils Conrad', 'Kindberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(46, 'Nils', 'Ahlström', '', '', 'Nils', 'Ahlström', NULL, NULL, NULL, NULL, NULL, NULL),
	(47, 'Olle', 'Mårtensson', '1915', '1995', 'Olle', 'Mårtensson', NULL, NULL, NULL, NULL, NULL, NULL),
	(48, 'Oswald', 'Sandberg', '', '', 'Oswald', 'Sandberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(49, 'Peter', 'Olsson', '1838', '1923', 'Peter', 'Olsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(50, 'Rudolf', 'Florin', '1894', '1965', 'Rudolf Karl', 'Florin', NULL, NULL, NULL, NULL, NULL, NULL),
	(51, 'Robert', 'Hartman', '1827', '1891', 'Robert Wilhelm', 'Hartman', NULL, NULL, NULL, NULL, NULL, NULL),
	(52, 'Sigfrid', 'Medelius', '1878', '1930', 'Sigfrid Olof', 'Medelius', NULL, NULL, NULL, NULL, NULL, NULL),
	(53, 'Thore Gustaf', 'Halle', '1884', '1964', 'Thore Gustaf', 'Halle', NULL, NULL, NULL, NULL, NULL, NULL),
	(55, 'Zdenek', 'Pilous', '1912', '2000', 'Zdenek', 'Pilous', NULL, NULL, NULL, NULL, NULL, NULL),
	(56, 'Fredrik Johan', 'Björnström', '1833', '1889', 'Fredrik Johan', 'Björnström', NULL, NULL, NULL, NULL, NULL, NULL),
	(57, 'Tycho', 'Vestergren', '1875', '1930', 'Jacob Tycho Conrad', 'Vestergren', NULL, NULL, NULL, NULL, NULL, NULL),
	(58, 'Knut', 'Kjellmark', '1866', '', 'Knut Bernhard', 'Kjellmark', NULL, NULL, NULL, NULL, NULL, NULL),
	(59, 'Oscar', 'Palmgren', '', '', 'Oscar', 'Palmgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(60, 'Åke', 'Strid', '1932', '', 'Åke', 'Strid', NULL, NULL, NULL, NULL, NULL, NULL),
	(62, 'Hugo', 'Thedenius', '1843', '1929', 'Carl Gustaf Hugo', 'Thedenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(63, 'Anders', 'Fryxell', '', '', 'Anders', 'Fryxell', NULL, NULL, NULL, NULL, NULL, NULL),
	(64, 'Gustaf Oskar', 'Malme', '', '', 'Gustaf Oskar', 'Andersson/ Malme', NULL, NULL, NULL, NULL, NULL, NULL),
	(65, 'Herman A.', 'Fröding', '', '', 'Herman A.', 'Fröding', NULL, NULL, NULL, NULL, NULL, NULL),
	(66, 'M.', 'Sandberg', '', '', 'M.', 'Sandberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(68, 'Gunnar Victor', 'Schotte', '1874', '1925', 'Gunnar Victor', 'Schotte', NULL, NULL, NULL, NULL, NULL, NULL),
	(69, 'F. Oscar', 'Österlind', '1886', '1965', 'F. Oscar', 'Österlind', NULL, NULL, NULL, NULL, NULL, NULL),
	(70, 'Pell Algot', 'Eriksson', '1919', '2004', 'Pell Algot', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(71, 'M.', 'Johansson', '', '', 'M.', 'Johansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(72, 'Herman Georg', 'Simmons', '1866', '1943', 'Herman Georg', 'Simmons', NULL, NULL, NULL, NULL, NULL, NULL),
	(73, 'Albert', 'Schumacher', '1893', '1975', 'Albert', 'Schumacher', NULL, NULL, NULL, NULL, NULL, NULL),
	(74, 'E.', 'Jørgensen', '', '', 'E.', 'Jørgensen', NULL, NULL, NULL, NULL, NULL, NULL),
	(75, 'Alan Cyril', 'Crunwell', '1923', '', 'Alan Cyril', 'Crunwell', NULL, NULL, NULL, NULL, NULL, NULL),
	(76, 'Sigfrid', 'Arnell', '1895', '1970', 'Sigfrid Wilhelm', 'Arnell', NULL, NULL, NULL, NULL, NULL, NULL),
	(78, 'I.', 'Fritje', '', '', 'I.', 'Fritje', NULL, NULL, NULL, NULL, NULL, NULL),
	(79, 'Edvard', 'af Hällström', '', '', 'Edvard', 'Hällström, af', NULL, NULL, NULL, NULL, NULL, NULL),
	(80, 'Sven', 'Berggren', '1837', '1917', 'Sven', 'Berggren', NULL, NULL, NULL, NULL, NULL, NULL),
	(81, 'Victor', 'Brotherus', '1849', '1929', 'Victor Ferdinand', 'Brotherus', NULL, NULL, NULL, NULL, NULL, NULL),
	(82, 'K.', 'Löfvander', '', '', 'K.', 'Löfvander', NULL, NULL, NULL, NULL, NULL, NULL),
	(83, 'Sextus Otto', 'Lindberg', '1835', '1889', 'Sextus Otto', 'Lindberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(84, 'A.', 'Wirén', '', '', 'A.', 'Wirén', NULL, NULL, NULL, NULL, NULL, NULL),
	(85, 'Carl Oscar', 'Hamnström', '1816', '1886', 'Carl Oscar', 'Hamnström', NULL, NULL, NULL, NULL, NULL, NULL),
	(86, 'Ingebrigt', 'Hagen', '1852', '1917', 'Ingebrigt Severin', 'Hagen', NULL, NULL, NULL, NULL, NULL, NULL),
	(87, 'Josef', 'Blumrich', '1865', '1949', 'Josef', 'Blumrich', NULL, NULL, NULL, NULL, NULL, NULL),
	(88, 'Lars', 'Westman', '', '', 'Lars', 'Westman', NULL, NULL, NULL, NULL, NULL, NULL),
	(89, 'Christian', 'Kaurin', '1831', '1898', 'Christian', 'Kaurin', NULL, NULL, NULL, NULL, NULL, NULL),
	(90, 'Stig', 'Waldheim', '1911', '1976', 'Stig', 'Waldheim', NULL, NULL, NULL, NULL, NULL, NULL),
	(91, 'Carl E.', 'Hjärne', '', '', 'Carl E.', 'Hjärne', NULL, NULL, NULL, NULL, NULL, NULL),
	(92, 'Robert', 'Tolf', '1849', '1903', 'Robert', 'Tolf', NULL, NULL, NULL, NULL, NULL, NULL),
	(93, 'Erik', 'Sturesson', '', '', 'Erik', 'Sturesson', NULL, NULL, NULL, NULL, NULL, NULL),
	(94, 'Sven Johan', 'Lindgren', '1810', '1849', 'Sven Johan', 'Lindgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(95, 'Nils', 'Albertson', '1909', '1956', 'Nils', 'Albertson', NULL, NULL, NULL, NULL, NULL, NULL),
	(96, 'C. A.', 'Geijer', '', '', 'C. A.', 'Geijer', NULL, NULL, NULL, NULL, NULL, NULL),
	(97, 'Tauno', 'Ulvinen', '1930', '', 'Tauno', 'Ulvinen', NULL, NULL, NULL, NULL, NULL, NULL),
	(98, 'J.', 'Stzotzer', '', '', 'J.', 'Stzotzer', NULL, NULL, NULL, NULL, NULL, NULL),
	(99, 'Gustaf', 'Öhrstedt', '1862', '', 'Gustaf', 'Öhrstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(100, 'Bror', 'Hedlin', '1922', '', 'Bror', 'Hedlin', NULL, NULL, NULL, NULL, NULL, NULL),
	(101, 'Birger', 'Kajanus', '1882', '1931', 'Birger', 'Nilson /Kajanus', NULL, NULL, NULL, NULL, NULL, NULL),
	(102, 'Fredrik', 'Lönnkvist', '1849', '', 'Fredrik', 'Lönnkvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(103, 'Sven Johan', 'Enander', '1847', '1928', 'Sven Johan', 'Enander', NULL, NULL, NULL, NULL, NULL, NULL),
	(104, 'A.', 'Grape', '', '', 'A.', 'Grape', NULL, NULL, NULL, NULL, NULL, NULL),
	(105, 'Florentin', 'Behm', '1838', '1915', 'Johan Eric Florentin', 'Behm', NULL, NULL, NULL, NULL, NULL, NULL),
	(106, 'Gerhard', 'Åberg', '1868', '1940', 'Johan Gerhard Göran', 'Åberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(107, 'Olof Johnsson', 'Hasslow', '1871', '1952', 'Olof Johnsson', 'Hasslow', NULL, NULL, NULL, NULL, NULL, NULL),
	(108, 'Hjalmar', 'Holmgren', '1822', '1885', 'Hjalmar Joseph', 'Holmgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(109, 'Karl Bernhard', 'Nordström', '1871', '1919', 'Karl Bernhard', 'Nordström', NULL, NULL, NULL, NULL, NULL, NULL),
	(110, 'Sten', 'Grapengiesser', '1868', '1955', 'Sten', 'Grapengiesser', NULL, NULL, NULL, NULL, NULL, NULL),
	(111, 'Hampus Wilhelm', 'Arnell', '1848', '1932', 'Hampus Wilhelm', 'Arnell', NULL, NULL, NULL, NULL, NULL, NULL),
	(112, 'Henrik', 'Sporrong', '', '', 'Henrik', 'Sporrong', NULL, NULL, NULL, NULL, NULL, NULL),
	(113, 'Carl Petter', 'Laestadius', '1835', '1920', 'Carl Petter', 'Laestadius', NULL, NULL, NULL, NULL, NULL, NULL),
	(114, 'Johan', 'Ångström', '1813', '1879', 'Johan', 'Ångström', NULL, NULL, NULL, NULL, NULL, NULL),
	(116, 'Dale H.', 'Vitt', '', '', 'Dale H.', 'Vitt', NULL, NULL, NULL, NULL, NULL, NULL),
	(117, 'Sixten', 'Bergström', '1878', '', 'Sixten', 'Bergström', NULL, NULL, NULL, NULL, NULL, NULL),
	(118, 'Fredrik Elias', 'Ahlvengren', '1862', '1921', 'Fredrik Elias', 'Ahlvengren', NULL, NULL, NULL, NULL, NULL, NULL),
	(119, 'Carl', 'Malmström', '', '', 'Carl', 'Malmström', NULL, NULL, NULL, NULL, NULL, NULL),
	(120, 'Emil Viktor', 'Ekstrand', '1841', '1884', 'Emil Viktor', 'Ekstrand', NULL, NULL, NULL, NULL, NULL, NULL),
	(121, 'John', 'Persson', '1854', '1930', 'John', 'Persson', NULL, NULL, NULL, NULL, NULL, NULL),
	(122, 'Johan Ernst', 'Palmér', '1863', '', 'Johan Ernst', 'Palmér', NULL, NULL, NULL, NULL, NULL, NULL),
	(123, 'John', 'Gustafsson', '', '', 'John', 'Gustafsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(124, 'Allan', 'Uggla', '1878', '1959', 'Allan', 'Uggla', NULL, NULL, NULL, NULL, NULL, NULL),
	(125, 'Magnus', 'Östman', '1852', '1927', 'Magnus', 'Östman', NULL, NULL, NULL, NULL, NULL, NULL),
	(126, 'Otto', 'Nordstedt', '1838', '1924', 'Carl Fredrik Otto', 'Nordstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(127, 'Gösta', 'Svensson', '1900', '', 'Gösta', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL),
	(128, 'Johan Richard', 'Jungner', '1858', '1929', 'Johan Richard', 'Jungner', NULL, NULL, NULL, NULL, NULL, NULL),
	(129, 'Nils', 'Alroth', '', '', 'Nils', 'Alroth', NULL, NULL, NULL, NULL, NULL, NULL),
	(130, 'Sven', 'Ekman', '', '', 'Sven', 'Ekman', NULL, NULL, NULL, NULL, NULL, NULL),
	(131, 'August', 'Hansen', '', '', 'August', 'Hansen', NULL, NULL, NULL, NULL, NULL, NULL),
	(132, 'Boye', 'Ström', '', '', 'Chr. Boye', 'Ström', NULL, NULL, NULL, NULL, NULL, NULL),
	(133, 'C. C.', 'Townsend', '1926', '', 'Clifford Charles', 'Townsend', NULL, NULL, NULL, NULL, NULL, NULL),
	(134, 'C.', 'Trautmann', '', '', 'C.', 'Trautmann', NULL, NULL, NULL, NULL, NULL, NULL),
	(135, 'Georg', 'Roth', '1842', '1915', 'Georg', 'Roth', NULL, NULL, NULL, NULL, NULL, NULL),
	(136, 'Göran', 'Englund', '', '', 'Göran', 'Englund', NULL, NULL, NULL, NULL, NULL, NULL),
	(137, 'Hjalmar', 'Mosén', '1841', '1887', 'Carl Wilhelm Hjalmar', 'Mosén', NULL, NULL, NULL, NULL, NULL, NULL),
	(138, 'Linnéa', 'Roswall', '', '', 'Linnéa', 'Roswall', NULL, NULL, NULL, NULL, NULL, NULL),
	(139, 'Niels', 'Bryhn', '1854', '1916', 'Niels', 'Bryhn', NULL, NULL, NULL, NULL, NULL, NULL),
	(140, 'Olof Gotthard', 'Blomberg', '1838', '1901', 'Olof Gotthard', 'Blomberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(141, 'Theodore', 'Suse', '', '', 'Theodore', 'Suse', NULL, NULL, NULL, NULL, NULL, NULL),
	(142, 'Per', 'Dusén', '1855', '1926', 'Per Karl Hjalmar', 'Dusén', NULL, NULL, NULL, NULL, NULL, NULL),
	(143, 'Berthold', 'Sundler', '', '', 'Berthold', 'Sundler', NULL, NULL, NULL, NULL, NULL, NULL),
	(144, 'Sonja', 'Dalvald', '', '', 'Sonja', 'Dalvald', NULL, NULL, NULL, NULL, NULL, NULL),
	(145, 'Karl Otto Edvard', 'Stenström', '1858', '1901', 'Karl Otto Edvard', 'Stenström', NULL, NULL, NULL, NULL, NULL, NULL),
	(146, 'Alfred', 'Callmé', '1860', '1889', 'Herman Alfred', 'Callmé', NULL, NULL, NULL, NULL, NULL, NULL),
	(147, 'Axel', 'Magnusson', '1817', '1909', 'Axel Alfred', 'Magnusson', NULL, NULL, NULL, NULL, NULL, NULL),
	(148, 'Sven', 'Brun', '', '', 'Sven', 'Brun', NULL, NULL, NULL, NULL, NULL, NULL),
	(149, 'Walther', 'Migula', '1863', '1938', 'Emil Friedrich August Walther', 'Migula', NULL, NULL, NULL, NULL, NULL, NULL),
	(150, 'M.', 'Toma', '1934', '', 'Mihai T.', 'Toma', NULL, NULL, NULL, NULL, NULL, NULL),
	(151, 'S. G.', 'Harrison', '', '', 'S. G.', 'Harrison', NULL, NULL, NULL, NULL, NULL, NULL),
	(152, 'Wilhelm', 'Freiberg', '1879', '1967', 'Wilhelm', 'Freiberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(153, 'N.', 'Alsthin', '', '', 'N.', 'Alsthin', NULL, NULL, NULL, NULL, NULL, NULL),
	(154, 'Oskar Vilhelm ?', 'Wennersten', '1867', '', 'Oskar Vilhelm ?', 'Wennersten', NULL, NULL, NULL, NULL, NULL, NULL),
	(155, 'A. F.', 'Liljeholm', '', '', 'A. F.', 'Liljeholm', NULL, NULL, NULL, NULL, NULL, NULL),
	(156, 'Olof Leopold', 'Sillén', '1813', '1894', 'Olof Leopold', 'Sillén', NULL, NULL, NULL, NULL, NULL, NULL),
	(157, 'Odo', 'Sundvik', '1880', '1913', 'Odo', 'Sundvik', NULL, NULL, NULL, NULL, NULL, NULL),
	(158, 'Randor Eretins', 'Fridtz', '1845', '1921', 'Randor Eretins', 'Fridtz', NULL, NULL, NULL, NULL, NULL, NULL),
	(159, 'Dale M. J.', 'Mueller', '', '', 'Dale M. J.', 'Mueller', NULL, NULL, NULL, NULL, NULL, NULL),
	(160, 'Ernst', 'Schön', '', '', 'Ernst', 'Schön', NULL, NULL, NULL, NULL, NULL, NULL),
	(161, 'Lennart', 'Wahlberg', '', '', 'Lennart', 'Wahlberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(162, 'Gustav', 'Fridner', '', '', 'Gustav', 'Fridner', NULL, NULL, NULL, NULL, NULL, NULL),
	(163, 'Marie', 'Muhr', '', '', 'Marie', 'Muhr', NULL, NULL, NULL, NULL, NULL, NULL),
	(164, 'Gustav', 'Sandberg', '', '', 'Gustav', 'Sandberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(165, 'Herman', 'Svenonius', '1879', '', 'Ture Herman Ludvig', 'Svenonius', NULL, NULL, NULL, NULL, NULL, NULL),
	(166, 'Markus', 'Forslund', '', '', 'Markus', 'Forslund', NULL, NULL, NULL, NULL, NULL, NULL),
	(167, '', '', '', '', 'Susanne', 'Rundlöf', NULL, NULL, NULL, NULL, NULL, NULL),
	(168, 'John Axel', 'Nannfeldt', '1904', '1985', 'John Axel Frithiof', 'Nannfeldt', NULL, NULL, NULL, NULL, NULL, NULL),
	(169, 'Carl Gustaf ?', 'Alm', '1888', '', 'Carl Gustaf ?', 'Alm', NULL, NULL, NULL, NULL, NULL, NULL),
	(170, 'Sten', 'Svenson', '', '', 'Sten', 'Svenson', NULL, NULL, NULL, NULL, NULL, NULL),
	(171, 'Hilda', 'Möller', '', '', 'Hilda', 'Möller', NULL, NULL, NULL, NULL, NULL, NULL),
	(172, 'Ernst', 'Hjertman', '', '', 'Ernst', 'Hjertman', NULL, NULL, NULL, NULL, NULL, NULL),
	(173, 'Hampus', 'von Post', '1822', '1911', 'Hampus Adolph von', 'Post', NULL, NULL, NULL, NULL, NULL, NULL),
	(174, 'Erik', 'Asplund', '1888', '1974', 'Erik', 'Asplund', NULL, NULL, NULL, NULL, NULL, NULL),
	(175, 'Fredrik', 'Elmqvist', '1844', '1904', 'Carl Fredrik', 'Elmqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(176, 'J.', 'Jeppesen', '', '', 'J.', 'Jeppesen', NULL, NULL, NULL, NULL, NULL, NULL),
	(177, 'Tapio', 'Laine', '1962', '', 'Tapio', 'Laine', NULL, NULL, NULL, NULL, NULL, NULL),
	(178, 'Friedrich', 'Wilms', '1848', '1919', 'Friedrich', 'Wilms', NULL, NULL, NULL, NULL, NULL, NULL),
	(179, 'Karl Adam Theodor', 'Seth', '1850', '1909', 'Karl Adam Theodor', 'Seth', NULL, NULL, NULL, NULL, NULL, NULL),
	(181, 'Thor-Björn', 'Engelmark', '', '', 'Thor-Björn', 'Engelmark', NULL, NULL, NULL, NULL, NULL, NULL),
	(182, 'Frantz', 'Kiær', '1835', '1893', 'Frantz Casper', 'Kiær', NULL, NULL, NULL, NULL, NULL, NULL),
	(183, 'Per Olof', 'Nyman', '', '', 'Per Olof', 'Nyman', NULL, NULL, NULL, NULL, NULL, NULL),
	(184, 'J. L.', 'Lagerkrantz', '', '', 'J. L.', 'Lagerkrantz', NULL, NULL, NULL, NULL, NULL, NULL),
	(185, 'Curt', 'Mossberg', '', '', 'Curt', 'Mossberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(186, 'Josef', 'Podpera', '1878', '1954', 'Josef', 'Podpera', NULL, NULL, NULL, NULL, NULL, NULL),
	(188, 'Carl Johan', 'Hartman', '1790', '1849', 'Carl Johan', 'Hartman', NULL, NULL, NULL, NULL, NULL, NULL),
	(189, 'William Joseph', 'Hoe', '1941', '', 'William Joseph', 'Hoe', NULL, NULL, NULL, NULL, NULL, NULL),
	(190, 'Christian Oscar', 'Strömholm', '1838', '1916', 'Christian Oscar', 'Strömholm', NULL, NULL, NULL, NULL, NULL, NULL),
	(191, 'Håkan', 'Lindström', '', '', 'Håkan', 'Lindström', NULL, NULL, NULL, NULL, NULL, NULL),
	(192, 'Karl Fredrik', 'Dusén', '1849', '1919', 'Karl Fredrik', 'Dusén', NULL, NULL, NULL, NULL, NULL, NULL),
	(193, 'Emil', 'Haglund', '', '', 'Emil', 'Haglund', NULL, NULL, NULL, NULL, NULL, NULL),
	(194, 'S. M.', 'Larsson', '', '', 'S. M.', 'Larsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(195, 'Caroline', 'Rosenberg', '1810', '1902', 'Caroline Friderike', 'Rosenberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(196, 'J.', 'Rekstad', '', '', 'J.', 'Rekstad', NULL, NULL, NULL, NULL, NULL, NULL),
	(197, 'Karl', 'Loitlesberger', '1857', '1943', 'Karl', 'Loitlesberger', NULL, NULL, NULL, NULL, NULL, NULL),
	(198, 'Maurice', 'Onraedt', '1904', '', 'Frère  Maurice, F.S.C.', 'Onraedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(199, 'J. A.', 'Lewin', '', '', 'J. A.', 'Lewin', NULL, NULL, NULL, NULL, NULL, NULL),
	(200, 'A. R.', 'Ruoranen', '', '', 'A. R.', 'Ruoranen', NULL, NULL, NULL, NULL, NULL, NULL),
	(201, 'Wolfgang', 'Bock', '', '', 'Wolfgang von', 'Bock', NULL, NULL, NULL, NULL, NULL, NULL),
	(202, 'Franz', 'Matouschek', '1871', '', 'Franz', 'Matouschek', NULL, NULL, NULL, NULL, NULL, NULL),
	(203, 'Bertil', 'Gaunitz', '', '', 'Bertil', 'Gaunitz', NULL, NULL, NULL, NULL, NULL, NULL),
	(204, 'Otto', 'Vesterlund', '1857', '1920', 'Per Otto', 'Vesterlund', NULL, NULL, NULL, NULL, NULL, NULL),
	(205, 'P. A.', 'Issén', '', '', 'P. A.', 'Issén', NULL, NULL, NULL, NULL, NULL, NULL),
	(206, 'Thorgny', 'Krok', '1834', '1921', 'Thorgny Ossian Bolivar Napoleon', 'Krok', NULL, NULL, NULL, NULL, NULL, NULL),
	(207, 'Gustav Alfred', 'Ringselle', '1868', '1944', 'Gustav Alfred', 'Ringselle', NULL, NULL, NULL, NULL, NULL, NULL),
	(208, 'And[..]', 'Björk [?]', '', '', 'And[..]', 'Björk [?]', NULL, NULL, NULL, NULL, NULL, NULL),
	(209, 'Isabelle', 'Tavares', '1921', '', 'Isabelle Irene', 'Tavares', NULL, NULL, NULL, NULL, NULL, NULL),
	(210, 'Reino', 'Fagerstén', '1931', '', 'Reino', 'Fagerstén', NULL, NULL, NULL, NULL, NULL, NULL),
	(211, 'C. F.', 'Arrhenius', '', '', 'C. F.', 'Arrhenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(212, 'Torsten', 'Sundin', '1893', '', 'Torsten Olov Helmfrid', 'Sundin', NULL, NULL, NULL, NULL, NULL, NULL),
	(213, 'Gustaf Einar', 'Du Rietz', '1895', '1967', 'Gustaf Einar', 'Du Rietz', NULL, NULL, NULL, NULL, NULL, NULL),
	(214, 'Erik', 'Collinder', '1848', '1920', 'Erik', 'Collinder', NULL, NULL, NULL, NULL, NULL, NULL),
	(215, 'Johan', 'Almqvist', '', '', 'Johan', 'Almqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(216, 'P.', 'Moson', '', '', 'P.', 'Moson', NULL, NULL, NULL, NULL, NULL, NULL),
	(218, 'Nils', 'Hakelier', '1929', '1995', 'Nils', 'Hakelier', NULL, NULL, NULL, NULL, NULL, NULL),
	(219, 'Søren', 'Sørensen', '1873', '1927', 'Søren', 'Sørensen', NULL, NULL, NULL, NULL, NULL, NULL),
	(220, 'N. J. ', 'Sehen[..]', '', '', 'N. J. ', 'Sehen[..]', NULL, NULL, NULL, NULL, NULL, NULL),
	(221, 'Unknown', '', '', '', 'Unknown', '', NULL, NULL, NULL, NULL, NULL, NULL),
	(224, 'A.', 'Halle', '', '', 'A.', 'Halle', NULL, NULL, NULL, NULL, NULL, NULL),
	(225, 'C. Alfred', 'Andersson', '', '', 'C. Alfred', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(226, 'Hans', 'Forsell', '1843', '1901', 'Hans', 'Forsell', NULL, NULL, NULL, NULL, NULL, NULL),
	(227, 'E.', 'Älviling', '', '', 'E.', 'Älviling', NULL, NULL, NULL, NULL, NULL, NULL),
	(228, 'Carl', 'Söderström', '', '', 'Carl', 'Söderström', NULL, NULL, NULL, NULL, NULL, NULL),
	(229, 'Hilding', 'Lundelius', '1892', '', 'Hilding Adolf', 'Lundelius', NULL, NULL, NULL, NULL, NULL, NULL),
	(230, 'Ragnar', 'Hult', '1857', '1899', 'Ragnar', 'Hult', NULL, NULL, NULL, NULL, NULL, NULL),
	(231, 'Edvard', 'von Krusentstjerna ', '1908', '1994', 'Axel Henrik Edvard Filip von', 'Krusentstjerna', NULL, NULL, NULL, NULL, NULL, NULL),
	(232, 'Per', 'Tufvesson', '1866', '1940', 'Per', 'Tufvesson', NULL, NULL, NULL, NULL, NULL, NULL),
	(233, 'N. Herman', 'Nilsson', '', '', 'N. Herman', 'Nilsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(234, 'Albert', 'Tullgren', '1874', '', 'Hugo Albert', 'Tullgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(235, 'E. L.', 'Larsson', '', '', 'E. L.', 'Larsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(236, 'Magnus Gustaf', 'Retzius', '1842', '1919', 'Magnus Gustaf', 'Retzius', NULL, NULL, NULL, NULL, NULL, NULL),
	(237, 'Ko.', 'Forster', '', '', 'Ko.', 'Forster', NULL, NULL, NULL, NULL, NULL, NULL),
	(238, 'Fredrik Wilhelm Christian', 'Areschoug', '1830', '1908', 'Fredrik Wilhelm Christian', 'Areschoug', NULL, NULL, NULL, NULL, NULL, NULL),
	(239, 'Fred ?', 'Liljenberg ?', '', '', 'Fred ?', 'Liljenberg ?', NULL, NULL, NULL, NULL, NULL, NULL),
	(240, 'Anna-Stina', 'Duerden', NULL, NULL, 'Anna-Stina', 'Duerden', NULL, NULL, NULL, NULL, NULL, NULL),
	(241, 'Wilhelm Philipp', 'Schimper', '1808', '1880', 'Wilhelm Philipp', 'Schimper', NULL, NULL, NULL, NULL, NULL, NULL),
	(242, 'Sven Axel', 'Tullberg', '1852', '1886', 'Sven Axel Teodor', 'Tullberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(243, 'The', 'Svedberg', '', '', 'The', 'Svedberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(244, 'Wilhelm Eugene', 'Berndes', '1844', '1882', 'Wilhelm Eugene', 'Berndes', NULL, NULL, NULL, NULL, NULL, NULL),
	(245, 'Claës Gustaf', 'Myrin', '1803', '1835', 'Claës Gustaf', 'Myrin', NULL, NULL, NULL, NULL, NULL, NULL),
	(246, 'Erland', 'Vetterhall', '1846', '', 'Johan Erland Vilhelm', 'Vetterhall', NULL, NULL, NULL, NULL, NULL, NULL),
	(247, 'Niilo', 'Söyrinki', '', '', 'Niilo', 'Söyrinki', NULL, NULL, NULL, NULL, NULL, NULL),
	(248, 'J.', 'Frymann', '', '', 'J.', 'Frymann', NULL, NULL, NULL, NULL, NULL, NULL),
	(249, 'Per', 'Hörstedt', '', '', 'Per', 'Hörstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(250, 'Axel Ludvig', 'Grönvall', '1838', '1892', 'Troed Axel Ludvig', 'Grönvall', NULL, NULL, NULL, NULL, NULL, NULL),
	(251, 'Kimmo', 'Tolonen', '1938', '', 'Kimmo', 'Tolonen', NULL, NULL, NULL, NULL, NULL, NULL),
	(252, 'O.', 'Davidsson', '', '', 'O.', 'Davidsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(253, 'Jan', 'Greve', '', '', 'Jan', 'Greve', NULL, NULL, NULL, NULL, NULL, NULL),
	(254, 'Victor', 'Schiffner', '1862', '1944', 'Victor Felix', 'Schiffner', NULL, NULL, NULL, NULL, NULL, NULL),
	(255, 'Kerstin', 'Kustås', '', '', 'Kerstin', 'Kustås', NULL, NULL, NULL, NULL, NULL, NULL),
	(256, 'Rolf', 'Santesson', '1916', '', 'Rolf', 'Santesson', NULL, NULL, NULL, NULL, NULL, NULL),
	(257, 'C. D.', 'Engelhart', '', '', 'C. D.', 'Engelhart', NULL, NULL, NULL, NULL, NULL, NULL),
	(258, '', 'marias', '', '', '', 'Marias', NULL, NULL, NULL, NULL, NULL, NULL),
	(259, 'Elling', 'Ryan', '1849', '1905', 'Elling', 'Ryan', NULL, NULL, NULL, NULL, NULL, NULL),
	(260, 'S. C', 'Sommerfeldt', '', '', 'S. C', 'Sommerfeldt', NULL, NULL, NULL, NULL, NULL, NULL),
	(261, 'Gunnar', 'Andersson', '', '', 'Gunnar', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(262, 'Ernst', 'Adlerz', '1854', '1818', 'Ernst', 'Adlerz', NULL, NULL, NULL, NULL, NULL, NULL),
	(263, 'Otto Rudolf', 'Holmberg', '1874', '1930', 'Otto Rudolf', 'Holmberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(264, 'Rud.', 'Oldberg', '', '', 'Rud.', 'Oldberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(265, 'Hans', 'Hollmén', '', '', 'Hans', 'Hollmén', NULL, NULL, NULL, NULL, NULL, NULL),
	(266, 'P ?', 'Thorin', '', '', 'P ?', 'Thorin', NULL, NULL, NULL, NULL, NULL, NULL),
	(267, 'Christian', 'Jensen', '1859', '1941', 'Christian Erasmus Otterstrøm', 'Jensen', NULL, NULL, NULL, NULL, NULL, NULL),
	(268, 'Paul', 'Culmann', '1860', '1936', 'Paul', 'Culmann', NULL, NULL, NULL, NULL, NULL, NULL),
	(269, 'Ignaz', 'Familler', '1863', '1923', 'Ignaz', 'Familler', NULL, NULL, NULL, NULL, NULL, NULL),
	(270, 'C. A.', 'Fredriksson', '', '', 'C. A.', 'Fredriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(271, 'Johan Alfred Zakarias', 'Brundin', '1871', '1950', 'Johan Alfred Zakarias', 'Brundin', NULL, NULL, NULL, NULL, NULL, NULL),
	(272, 'Henrik Gustaf ?', 'Lübeck ', '1809', '1900', 'Henrik Gustaf ?', 'Lübeck ', NULL, NULL, NULL, NULL, NULL, NULL),
	(273, 'Martti', 'Ohenoja', '1933', '', 'Martti', 'Ohenoja', NULL, NULL, NULL, NULL, NULL, NULL),
	(274, 'Rudy G.', 'Koch', '1939', '', 'Rudy G.', 'Koch', NULL, NULL, NULL, NULL, NULL, NULL),
	(275, 'A.', 'Wälde', '', '', 'A.', 'Wälde', NULL, NULL, NULL, NULL, NULL, NULL),
	(276, 'Adolf', 'Hassler', '', '', 'Adolf', 'Hassler', NULL, NULL, NULL, NULL, NULL, NULL),
	(277, 'Sten-Sture', 'Forsell', '', '', 'Sten-Sture', 'Forsell', NULL, NULL, NULL, NULL, NULL, NULL),
	(278, 'Bengt', 'Lidforss', '1868', '1911', 'Bengt', 'Lidforss', NULL, NULL, NULL, NULL, NULL, NULL),
	(279, 'A. R.', 'Dahlgren', '', '', 'A. R.', 'Dahlgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(280, 'Nils Johan', 'Scheutz', '1836', '1889', 'Nils Johan Wilhelm', 'Scheutz', NULL, NULL, NULL, NULL, NULL, NULL),
	(281, 'Karl', 'Bergner', '', '', 'Karl', 'Bergner', NULL, NULL, NULL, NULL, NULL, NULL),
	(282, 'C.', 'Grebe', '', '', 'C.', 'Grebe', NULL, NULL, NULL, NULL, NULL, NULL),
	(283, 'E.', 'Lamy', '', '', 'E.', 'Lamy', NULL, NULL, NULL, NULL, NULL, NULL),
	(284, 'Carl', 'Warnstorf', '1837', '1921', 'Carl Friedrich E.', 'Warnstorf', NULL, NULL, NULL, NULL, NULL, NULL),
	(285, 'G.', 'Braun', '', '', 'G.', 'Braun', NULL, NULL, NULL, NULL, NULL, NULL),
	(286, 'Rikard', 'Sterner', '1891', '1956', 'Karl Rikard', 'Sterner', NULL, NULL, NULL, NULL, NULL, NULL),
	(287, 'Mauno J.', 'Kotilainen', '1895', '1961', 'Mauno Johannes', 'Kotilainen', NULL, NULL, NULL, NULL, NULL, NULL),
	(288, 'Paul O.', 'Schallert', '1879', '1970', 'Paul Otto', 'Schallert', NULL, NULL, NULL, NULL, NULL, NULL),
	(289, '', 'Herter', '', '', '', 'Herter', NULL, NULL, NULL, NULL, NULL, NULL),
	(290, 'Hans', 'Hupke', '1888', '1976', 'Hans', 'Hupke', NULL, NULL, NULL, NULL, NULL, NULL),
	(291, 'Lajos', 'Felföldy', '1920', '', 'Lajos J. M.', 'Felföldy', NULL, NULL, NULL, NULL, NULL, NULL),
	(292, 'Onraedt Maurice', 'Frère', '', '', 'Onraedt Maurice', 'Frère', NULL, NULL, NULL, NULL, NULL, NULL),
	(293, 'Cl.', 'Leredde', '', '', 'Cl.', 'Leredde', NULL, NULL, NULL, NULL, NULL, NULL),
	(294, 'Anders Johan', 'Malmgren', '1834', '1897', 'Anders Johan', 'Malmgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(295, 'Nicklas', 'Lönnell', '', '', 'Nicklas', 'Lönnell', NULL, NULL, NULL, NULL, NULL, NULL),
	(297, 'R.', 'Ratthe', '', '', 'R.', 'Ratthe', NULL, NULL, NULL, NULL, NULL, NULL),
	(298, 'Per Theodor', 'Cleve', '1840', '1905', 'Per Theodor', 'Cleve', NULL, NULL, NULL, NULL, NULL, NULL),
	(299, 'Thore Christian Elias', 'Fries', '1886', '1930', 'Thore Christian Elias', 'Fries', NULL, NULL, NULL, NULL, NULL, NULL),
	(300, 'August Henning', 'Weimarck', '1903', '1980', 'August Henning', 'Weimarck', NULL, NULL, NULL, NULL, NULL, NULL),
	(301, 'Jan', 'Elveland', '', '', 'Jan', 'Elveland', NULL, NULL, NULL, NULL, NULL, NULL),
	(302, 'G.', 'Herpel', '', '', 'G.', 'Herpel', NULL, NULL, NULL, NULL, NULL, NULL),
	(303, 'R. K.', 'Godfrey', '', '', 'R. K.', 'Godfrey', NULL, NULL, NULL, NULL, NULL, NULL),
	(305, 'Walter', 'Kiener', '1894', '1959', 'Walter Bigler', 'Kiener', NULL, NULL, NULL, NULL, NULL, NULL),
	(306, '', 'Kern', '', '', '', 'Kern', NULL, NULL, NULL, NULL, NULL, NULL),
	(307, 'Johan Edvard', 'Strandmark', '1845', '', 'Johan Edvard', 'Strandmark', NULL, NULL, NULL, NULL, NULL, NULL),
	(309, 'Ove E.', 'Eriksson', '1935', '', 'Ove E.', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(310, 'Axel', 'Granberg', '', '', 'Axel', 'Granberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(311, 'Rudolf R:son', 'Vallquist', '', '', 'Rudolf R:son', 'Vallquist', NULL, NULL, NULL, NULL, NULL, NULL),
	(312, 'Axel', 'Larsson', '', '', 'Axel', 'Larsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(313, 'Fritz', 'Agelin', '1876', '1948', 'Fritz', 'Agelin', NULL, NULL, NULL, NULL, NULL, NULL),
	(314, 'Lars Johan', 'Wahlstedt', '1836', '1917', 'Lars Johan', 'Wahlstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(315, 'Lars', 'Hedenäs', '1957', '', 'Lars Gustaf', 'Hedenäs', NULL, NULL, NULL, NULL, NULL, NULL),
	(316, 'Johan Petter', 'Norrlin', '1842', '1917', 'Johan Petter', 'Norrlin', NULL, NULL, NULL, NULL, NULL, NULL),
	(317, 'Henry', 'Conard', '1874', '1971', 'Henry Shoemaker', 'Conard', NULL, NULL, NULL, NULL, NULL, NULL),
	(318, 'Thorsten', 'Arwidsson', '1904', '1948', 'Thorsten', 'Arwidsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(319, 'Hany', 'Brensson', '', '', 'Hany', 'Brensson', NULL, NULL, NULL, NULL, NULL, NULL),
	(320, 'Carl August Emanuel', 'Lenström', '1848', '', 'Carl August Emanuel', 'Lenström', NULL, NULL, NULL, NULL, NULL, NULL),
	(321, 'K.', 'Laaksonen', '', '', 'K.', 'Laaksonen', NULL, NULL, NULL, NULL, NULL, NULL),
	(322, 'G.', 'Lång', '', '', 'G.', 'Lång', NULL, NULL, NULL, NULL, NULL, NULL),
	(323, 'L.', 'Philibert', '', '', 'L.', 'Philibert', NULL, NULL, NULL, NULL, NULL, NULL),
	(324, 'Sven', 'Kilander', '1917', '', 'Sven', 'Kilander', NULL, NULL, NULL, NULL, NULL, NULL),
	(325, 'Wick.', 'Berndal', '', '', 'Wick.', 'Berndal', NULL, NULL, NULL, NULL, NULL, NULL),
	(326, 'Carl', 'Baenitz', '1837', '1913', 'Carl Gabriel', 'Baenitz', NULL, NULL, NULL, NULL, NULL, NULL),
	(327, 'Svante', 'Larsson', '', '', 'Svante', 'Larsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(328, 'Herman', 'Persson', '', '', 'Herman', 'Persson', NULL, NULL, NULL, NULL, NULL, NULL),
	(329, 'Erik Leonard', 'Ekman', '1883', '1931', 'Erik Leonard', 'Ekman', NULL, NULL, NULL, NULL, NULL, NULL),
	(330, 'Johann', 'Breidler', '1828', '1913', 'Johann', 'Breidler', NULL, NULL, NULL, NULL, NULL, NULL),
	(331, 'Erik', 'Wall', '1971', '1959', 'Erik', 'Wall', NULL, NULL, NULL, NULL, NULL, NULL),
	(332, 'Joachim', 'Åkerman', '1798', '1876', 'Joachim', 'Åkerman', NULL, NULL, NULL, NULL, NULL, NULL),
	(333, 'Oetz', 'Ripurger', '', '', 'Oetz', 'Ripurger', NULL, NULL, NULL, NULL, NULL, NULL),
	(334, 'H.', 'Ekman', '', '', 'H.', 'Ekman', NULL, NULL, NULL, NULL, NULL, NULL),
	(335, 'A.', 'Roth', '', '', 'A.', 'Roth', NULL, NULL, NULL, NULL, NULL, NULL),
	(336, 'Clas Carl Gustaf', 'Kurck', '1849', '', 'Clas Carl Gustaf', 'Kurck', NULL, NULL, NULL, NULL, NULL, NULL),
	(337, 'Johan Gottfrid', 'Gunnarsson', '1866', '1944', 'Johan Gottfrid', 'Gunnarsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(338, 'Erik Gustaf', 'Almquist', '1892', '1974', 'Erik Gustaf', 'Almquist', NULL, NULL, NULL, NULL, NULL, NULL),
	(339, 'Wilhelm R.', 'Uggla', '1880', '1957', 'Wilhelm R.', 'Uggla', NULL, NULL, NULL, NULL, NULL, NULL),
	(340, 'F. A.', 'Artaria', '', '', 'F. A.', 'Artaria', NULL, NULL, NULL, NULL, NULL, NULL),
	(341, 'Stanley Wilson', 'Greene', '1928', '1989', 'Stanley Wilson', 'Greene', NULL, NULL, NULL, NULL, NULL, NULL),
	(342, 'Astrid', 'Cleve von Euler', '1875', '1968', 'Astrid Maira', 'Cleve / Cleve von Euler', NULL, NULL, NULL, NULL, NULL, NULL),
	(343, 'Josef', 'Duda', '1925', '', 'Josef', 'Duda', NULL, NULL, NULL, NULL, NULL, NULL),
	(344, 'S. W. C. ', '', '', '', 'S. W. C. ', '', NULL, NULL, NULL, NULL, NULL, NULL),
	(345, 'R. v.', 'Bahr', '', '', 'R. v.', 'Bahr', NULL, NULL, NULL, NULL, NULL, NULL),
	(346, 'C.', 'Pleijel', '', '', 'C.', 'Pleijel', NULL, NULL, NULL, NULL, NULL, NULL),
	(347, 'Sofie', 'Möller', '', '', 'Sofie', 'Möller', NULL, NULL, NULL, NULL, NULL, NULL),
	(348, 'Nils', 'Wulfsberg', '1847', '1888', 'Nils Gregers Ingvald', 'Wulfsberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(349, 'August', 'Vilke', '1868', '', 'August', 'Vilke', NULL, NULL, NULL, NULL, NULL, NULL),
	(350, 'W.', 'Bertram', '', '', 'W.', 'Bertram', NULL, NULL, NULL, NULL, NULL, NULL),
	(351, 'Arvid', 'Nymansson', '', '', 'Arvid', 'Nymansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(352, 'L.', 'Corbière', '', '', 'L.', 'Corbière', NULL, NULL, NULL, NULL, NULL, NULL),
	(353, 'August', 'Heintze', '', '', 'Sven August', 'Heintze', NULL, NULL, NULL, NULL, NULL, NULL),
	(354, 'J.', 'Weber', '', '', 'J.', 'Weber', NULL, NULL, NULL, NULL, NULL, NULL),
	(355, 'K. W.', 'K. W. Allison', '', '', 'Kenneth Willmay', 'Allison', NULL, NULL, NULL, NULL, NULL, NULL),
	(356, 'Göran', 'Wahlenberg', '1780', '1851', 'Göran', 'Wahlenberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(357, 'P.', 'Janzen', '', '', 'P.', 'Janzen', NULL, NULL, NULL, NULL, NULL, NULL),
	(358, 'Lennart', 'Wikström', '', '', 'Lennart', 'Wikström', NULL, NULL, NULL, NULL, NULL, NULL),
	(359, 'C. E.', 'Gustafsson', '', '', 'C. E.', 'Gustafsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(360, 'Johan', 'Möller', '', '', 'Johan', 'Möller', NULL, NULL, NULL, NULL, NULL, NULL),
	(361, 'Hervid', 'Vallin', '', '', 'Hervid', 'Vallin', NULL, NULL, NULL, NULL, NULL, NULL),
	(362, 'Carl', 'Lindman', '1856', '1928', 'Carl Axel Magnus', 'Lindman', NULL, NULL, NULL, NULL, NULL, NULL),
	(363, 'H. F. G.', 'Strömfelt', '', '', 'H. F. G.', 'Strömfelt', NULL, NULL, NULL, NULL, NULL, NULL),
	(364, 'Oskar', 'Lindén', '', '', 'Oskar', 'Lindén', NULL, NULL, NULL, NULL, NULL, NULL),
	(365, 'G.', 'Vesterlund', '', '', 'G.', 'Vesterlund', NULL, NULL, NULL, NULL, NULL, NULL),
	(366, 'A.', 'Kornerip', '', '', 'A.', 'Kornerip', NULL, NULL, NULL, NULL, NULL, NULL),
	(367, 'Hugo', 'Graf', '', '', 'Hugo', 'Graf', NULL, NULL, NULL, NULL, NULL, NULL),
	(368, 'J. W.', 'Davis', '', '', 'J. W.', 'Davis', NULL, NULL, NULL, NULL, NULL, NULL),
	(369, '', 'Widegren', '', '', '', 'Widegren', NULL, NULL, NULL, NULL, NULL, NULL),
	(370, 'A.', 'Topitz', '', '', 'A.', 'Topitz', NULL, NULL, NULL, NULL, NULL, NULL),
	(371, 'W. N.', 'Bonner', '', '', 'W. N.', 'Bonner', NULL, NULL, NULL, NULL, NULL, NULL),
	(372, 'Hans', 'Buch', '', '', 'Hans Robert Viktor', 'Buch', NULL, NULL, NULL, NULL, NULL, NULL),
	(374, 'J.', 'Lagergren', '', '', 'J.', 'Lagergren', NULL, NULL, NULL, NULL, NULL, NULL),
	(375, 'Ch.', 'Meylan', '', '', 'Ch.', 'Meylan', NULL, NULL, NULL, NULL, NULL, NULL),
	(376, 'Astrid', 'Åström', '', '', 'Astrid', 'Åström', NULL, NULL, NULL, NULL, NULL, NULL),
	(377, 'Ingvor', 'Christoffersson', '', '', 'Ingvor', 'Christoffersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(378, 'Hugo', 'Dahlstedt', '1856', '1934', 'Hugo Gustaf Adolf', 'Dahlstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(379, 'A. T.', 'Björkman', '', '', 'A. T.', 'Björkman', NULL, NULL, NULL, NULL, NULL, NULL),
	(380, 'Hans', 'Wachtmeister', '', '', 'Hans', 'Wachtmeister', NULL, NULL, NULL, NULL, NULL, NULL),
	(381, 'Alan Roy', 'Perry', '1938', '', 'Alan Roy', 'Perry', NULL, NULL, NULL, NULL, NULL, NULL),
	(382, 'Lars Levi', 'Laestadius', '1800', '1861', 'Lars Levi', 'Laestadius', NULL, NULL, NULL, NULL, NULL, NULL),
	(383, 'Harry', 'Smith', '', '', 'Harry', 'Smith', NULL, NULL, NULL, NULL, NULL, NULL),
	(384, 'S. L', 'Sjögren', '', '', 'S. L', 'Sjögren', NULL, NULL, NULL, NULL, NULL, NULL),
	(385, 'Foerster', 'Arnold', '1810', '1884', 'Foerster', 'Arnold', NULL, NULL, NULL, NULL, NULL, NULL),
	(386, 'Rich.', 'Picbauer', '', '', 'Rich.', 'Picbauer', NULL, NULL, NULL, NULL, NULL, NULL),
	(387, 'Hans M.', 'Fuchs', '', '', 'Hans M.', 'Fuchs', NULL, NULL, NULL, NULL, NULL, NULL),
	(388, 'A.', 'Troén', '', '', 'A.', 'Troén', NULL, NULL, NULL, NULL, NULL, NULL),
	(389, 'Gustaf', 'Malmgren', '', '', 'Gustaf', 'Malmgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(390, 'Conrad', 'Indebetou', '1801', '1893', 'Conrad Govert', 'Indebetou', NULL, NULL, NULL, NULL, NULL, NULL),
	(391, 'Ch.', 'd\'Alliezette', '', '', 'Ch.', 'd\'Alliezette', NULL, NULL, NULL, NULL, NULL, NULL),
	(392, 'Gust.', 'Schellenberg', '1882', '1963', 'Gust.', 'Schellenberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(393, 'Thorild', 'Wulff', '1877', '1917', 'Thorild', 'Wulff', NULL, NULL, NULL, NULL, NULL, NULL),
	(394, 'Bfarrer', 'Remmler', '', '', 'Bfarrer', 'Remmler', NULL, NULL, NULL, NULL, NULL, NULL),
	(395, 'Joseph', 'Bornmüller', '1862', '1948', 'Joseph Friedrich Nicolaus', 'Bornmüller', NULL, NULL, NULL, NULL, NULL, NULL),
	(396, 'G.', 'Björling', '', '', 'G.', 'Björling', NULL, NULL, NULL, NULL, NULL, NULL),
	(397, 'Josef', 'Jedlicka', '1912', '1959', 'Josef', 'Jedlicka', NULL, NULL, NULL, NULL, NULL, NULL),
	(398, 'Matthias Numsen', 'Blytt', '1789', '1862', 'Matthias Numsen', 'Blytt', NULL, NULL, NULL, NULL, NULL, NULL),
	(399, 'Zekta ?', 'Zchentz ?', '', '', 'Zekta ?', 'Zchentz ?', NULL, NULL, NULL, NULL, NULL, NULL),
	(400, 'Henri Viktor', 'Rosendahl', '1855', '1918', 'Henri Viktor', 'Rosendahl', NULL, NULL, NULL, NULL, NULL, NULL),
	(401, 'Axel', 'Blytt', '1843', '1898', 'Axel Gudbrand', 'Blytt', NULL, NULL, NULL, NULL, NULL, NULL),
	(402, 'P. G.', 'Lorentz', '', '', 'P. G.', 'Lorentz', NULL, NULL, NULL, NULL, NULL, NULL),
	(403, 'Paul C.', 'Hutchison', '', '', 'Paul C.', 'Hutchison', NULL, NULL, NULL, NULL, NULL, NULL),
	(404, 'C. H.', 'Godet', '', '', 'C. H.', 'Godet', NULL, NULL, NULL, NULL, NULL, NULL),
	(405, 'J.', 'Meleg', '', '', 'J.', 'Meleg', NULL, NULL, NULL, NULL, NULL, NULL),
	(406, '', '', '', '', '', 'Berndes & Engelhart', NULL, NULL, NULL, NULL, NULL, NULL),
	(407, 'A.', 'Sandvall', '', '', 'A.', 'Sandvall', NULL, NULL, NULL, NULL, NULL, NULL),
	(408, 'Erik', 'Persson', '', '', 'Erik', 'Persson', NULL, NULL, NULL, NULL, NULL, NULL),
	(409, 'S.', 'Leskinen', '', '', 'S.', 'Leskinen', NULL, NULL, NULL, NULL, NULL, NULL),
	(410, 'Robert Fredric', 'Fridstedt', '1832', '1893', 'Robert Fredric', 'Fridstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(411, 'C. O.', 'Lovén', '', '', 'C. O.', 'Lovén', NULL, NULL, NULL, NULL, NULL, NULL),
	(412, 'Sigrid', 'Cedergren', '', '', 'Sigrid', 'Cedergren', NULL, NULL, NULL, NULL, NULL, NULL),
	(414, 'Gillis', 'Een', '', '', 'Gillis', 'Een', NULL, NULL, NULL, NULL, NULL, NULL),
	(415, 'Carl Alex', 'Bergström', '1882', '1936', 'Carl Alex', 'Bergström', NULL, NULL, NULL, NULL, NULL, NULL),
	(416, 'Bertil', 'Lindquist', '1904', '', 'Bertil', 'Lindquist', NULL, NULL, NULL, NULL, NULL, NULL),
	(417, 'N.', 'Malts', '', '', 'N.', 'Malts', NULL, NULL, NULL, NULL, NULL, NULL),
	(418, 'Eric', 'Wahlén', '1842', '1891', 'Erik Hugo Eberhard', 'Wahlén', NULL, NULL, NULL, NULL, NULL, NULL),
	(419, 'August', 'Kopsch', '1913', '', 'August', 'Kopsch', NULL, NULL, NULL, NULL, NULL, NULL),
	(420, 'Juha', 'Viramo', '', '', 'Juha', 'Viramo', NULL, NULL, NULL, NULL, NULL, NULL),
	(421, 'Ph.', 'Vosselmann', '', '', 'Ph.', 'Vosselmann', NULL, NULL, NULL, NULL, NULL, NULL),
	(422, 'M.', 'Bettg', '', '', 'M.', 'Bettg', NULL, NULL, NULL, NULL, NULL, NULL),
	(425, 'L. [?]', 'Andersfors [?]', '', '', 'L. [?]', 'Andersfors [?]', NULL, NULL, NULL, NULL, NULL, NULL),
	(426, 'C.', 'Brandel', '', '', 'C.', 'Brandel', NULL, NULL, NULL, NULL, NULL, NULL),
	(427, 'Tor Åke', 'Tengwall', '', '', 'Tor Åke', 'Tengwall', NULL, NULL, NULL, NULL, NULL, NULL),
	(428, 'Lauri', 'Lektonen', '', '', 'Lauri', 'Lektonen', NULL, NULL, NULL, NULL, NULL, NULL),
	(429, 'Thore', 'Gustafson', '', '', 'Thore', 'Gustafson', NULL, NULL, NULL, NULL, NULL, NULL),
	(430, 'Ingrid', 'Berg', '', '', 'Ingrid', 'Berg', NULL, NULL, NULL, NULL, NULL, NULL),
	(431, 'Risto', 'Tuomikoski', '1911', '1989', 'Risto Kalevi', 'Tuomikoski', NULL, NULL, NULL, NULL, NULL, NULL),
	(432, 'Per-Anders', 'Esseen', '', '', 'Per-Anders', 'Esseen', NULL, NULL, NULL, NULL, NULL, NULL),
	(433, 'Arent', 'Silfversparre', '1892', '1958', 'Arent', 'Silfversparre', NULL, NULL, NULL, NULL, NULL, NULL),
	(434, 'G.', 'Bågenholm', '', '', 'G.', 'Bågenholm', NULL, NULL, NULL, NULL, NULL, NULL),
	(435, 'Pehr Johan', 'Hellbom', '1827', '1903', 'Pehr Johan', 'Hellbom', NULL, NULL, NULL, NULL, NULL, NULL),
	(436, 'Per', 'Löfgren', '', '', 'Per', 'Löfgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(437, 'Bengt', 'Danielsson', '', '', 'Bengt', 'Danielsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(438, 'Olof H.', 'Selling', '1917', '', 'Olof Hugo', 'Selling', NULL, NULL, NULL, NULL, NULL, NULL),
	(440, 'Th.', 'Rydén', '', '', 'Th.', 'Rydén', NULL, NULL, NULL, NULL, NULL, NULL),
	(442, 'Gunnar', 'Wistrand', '', '', 'Gunnar', 'Wistrand', NULL, NULL, NULL, NULL, NULL, NULL),
	(443, '', 'Zethelius', '', '', '', 'Zethelius', NULL, NULL, NULL, NULL, NULL, NULL),
	(444, 'C. J.', 'Arrhenius', '', '', 'C. J.', 'Arrhenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(445, 'F.', 'Eriksson', '', '', 'F.', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(446, 'Sven Olof', 'Blomqvist', '', '', 'Sven Olof', 'Blomqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(447, 'Sten', 'Wahlberg', '', '', 'Sten', 'Wahlberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(448, 'B. W.', 'Oreen', '', '', 'B. W.', 'Oreen', NULL, NULL, NULL, NULL, NULL, NULL),
	(449, 'Ragnar', 'Ohlsén', '1875', '1957', 'Ragnar', 'Ohlsén', NULL, NULL, NULL, NULL, NULL, NULL),
	(450, 'Verner V. V.', 'Wahlbeck', '', '', 'Verner V. V.', 'Wahlbeck', NULL, NULL, NULL, NULL, NULL, NULL),
	(451, 'Kristin', 'Palmqvist', '', '', 'Kristin', 'Palmqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(452, 'Martin', 'Johansson', '', '', 'Martin', 'Johansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(453, 'Allan', 'Nicklasson', '', '', 'Allan', 'Nicklasson', NULL, NULL, NULL, NULL, NULL, NULL),
	(454, 'G. v.', 'Niessel', '', '', 'G. v.', 'Niessel', NULL, NULL, NULL, NULL, NULL, NULL),
	(455, 'Katarina', 'Stenman', '', '', 'Katarina', 'Stenman', NULL, NULL, NULL, NULL, NULL, NULL),
	(456, 'P. H.', 'Strömman', '', '', 'P. H.', 'Strömman', NULL, NULL, NULL, NULL, NULL, NULL),
	(457, 'Gösta', 'Jönsson', '', '', 'Gösta', 'Jönsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(458, 'John', 'Agelii', '', '', 'John', 'Agelii', NULL, NULL, NULL, NULL, NULL, NULL),
	(459, 'D.', 'Bauer', '', '', 'D.', 'Bauer', NULL, NULL, NULL, NULL, NULL, NULL),
	(460, 'G. W', 'Nyman', '', '', 'G. W', 'Nyman', NULL, NULL, NULL, NULL, NULL, NULL),
	(461, 'R.', 'Ruoramen', '', '', 'R.', 'Ruoramen', NULL, NULL, NULL, NULL, NULL, NULL),
	(462, 'Walter M.', 'Linnaniemi', '', '', 'Walter M.', 'Linnaniemi', NULL, NULL, NULL, NULL, NULL, NULL),
	(463, 'Doyle E.', 'Anderegg', '1930', '', 'Doyle E.', 'Anderegg', NULL, NULL, NULL, NULL, NULL, NULL),
	(464, 'H. F.', 'Paulsen', '', '', 'H. F.', 'Paulsen', NULL, NULL, NULL, NULL, NULL, NULL),
	(465, 'J.', 'Pernn.', '', '', 'J.', 'Pernn.', NULL, NULL, NULL, NULL, NULL, NULL),
	(466, 'Fr.', 'Palzell', '', '', 'Fr.', 'Palzell', NULL, NULL, NULL, NULL, NULL, NULL),
	(467, 'Axel', 'Vinge', '1857', '1920', 'Nils Axel', 'Vinge', NULL, NULL, NULL, NULL, NULL, NULL),
	(468, 'Johan Oskar', 'Bomansson', '1838', '1906', 'Johan Oskar', 'Bomansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(469, 'Salomon Eberhard', 'Henschen', '1847', '1930', 'Salomon Eberhard', 'Henschen', NULL, NULL, NULL, NULL, NULL, NULL),
	(470, 'W.', 'Schemmann.', '', '', 'W.', 'Schemmann.', NULL, NULL, NULL, NULL, NULL, NULL),
	(471, 'Maurice', 'Bizot', '1905', '1979', 'Maurice Louis Jean', 'Bizot', NULL, NULL, NULL, NULL, NULL, NULL),
	(472, 'Royne', 'Andersson', '', '', 'Royne', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(473, 'A.', 'Boswell', '', '', 'A.', 'Boswell', NULL, NULL, NULL, NULL, NULL, NULL),
	(474, 'Fred W.', 'Gray', '1878', '', 'Frederick William', 'Gray', NULL, NULL, NULL, NULL, NULL, NULL),
	(475, 'Ferdinand', 'Schenk', '1867', '1935', 'Ferdinand', 'Schenk', NULL, NULL, NULL, NULL, NULL, NULL),
	(476, 'Wald.', 'Granberg', '', '', 'Wald.', 'Granberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(477, 'Hippolyte', 'Dupret.', '1853', '1932', 'Franois Hippolyte', 'Dupret.', NULL, NULL, NULL, NULL, NULL, NULL),
	(478, 'Albert', 'Falk', '', '', 'Albert', 'Falk', NULL, NULL, NULL, NULL, NULL, NULL),
	(479, 'P.', 'Hebert', '', '', 'P.', 'Hebert', NULL, NULL, NULL, NULL, NULL, NULL),
	(480, 'C. A.', 'Strömbäck', '', '', 'C. A.', 'Strömbäck', NULL, NULL, NULL, NULL, NULL, NULL),
	(482, 'A.', 'Osenius', '', '', 'A.', 'Osenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(483, 'Gustaf', 'Johansson', '', '', 'Gustaf', 'Johansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(484, 'K. R. J.', 'Forsell', '', '', 'K. R. J.', 'Forsell', NULL, NULL, NULL, NULL, NULL, NULL),
	(485, 'Johan', 'Leksell', '', '', 'Johan', 'Leksell', NULL, NULL, NULL, NULL, NULL, NULL),
	(486, 'Emil', 'Olin', '', '', 'Emil', 'Olin', NULL, NULL, NULL, NULL, NULL, NULL),
	(487, 'Hjalmar', 'Borg', '', '', 'Hjalmar', 'Borg', NULL, NULL, NULL, NULL, NULL, NULL),
	(488, 'O.', 'Wernberg', '', '', 'O.', 'Wernberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(489, 'A.', 'Walther', '', '', 'A.', 'Walther', NULL, NULL, NULL, NULL, NULL, NULL),
	(490, 'C. J.', 'Horning', '', '', 'C. J.', 'Horning', NULL, NULL, NULL, NULL, NULL, NULL),
	(491, 'H.', 'Björnström', '', '', 'H.', 'Björnström', NULL, NULL, NULL, NULL, NULL, NULL),
	(492, 'Otto', 'Gertz', '', '', 'Otto', 'Gertz', NULL, NULL, NULL, NULL, NULL, NULL),
	(493, 'Kaj W.', 'Larsen', '', '', 'Kaj W.', 'Larsen', NULL, NULL, NULL, NULL, NULL, NULL),
	(494, 'Gunnar', 'Lohammar', '', '', 'Gunnar', 'Lohammar', NULL, NULL, NULL, NULL, NULL, NULL),
	(495, 'Knut', 'Kjellberg', '', '', 'Knut', 'Kjellberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(496, 'P.', 'Dreesen', '', '', 'P.', 'Dreesen', NULL, NULL, NULL, NULL, NULL, NULL),
	(497, 'V.', 'Brehm', '', '', 'V.', 'Brehm', NULL, NULL, NULL, NULL, NULL, NULL),
	(498, 'Julius', 'Glowacki', '1846', '1915', 'Julius', 'Glowacki', NULL, NULL, NULL, NULL, NULL, NULL),
	(499, 'Viktor von', 'Cypers', '', '', 'Viktor', 'Cypers von Landrecy', NULL, NULL, NULL, NULL, NULL, NULL),
	(500, 'J.', 'Casch.', '', '', 'J.', 'Casch.', NULL, NULL, NULL, NULL, NULL, NULL),
	(501, 'Anders', 'Roland', '', '', 'Anders', 'Roland', NULL, NULL, NULL, NULL, NULL, NULL),
	(502, 'Paul Leslie', 'Redfearn, jr.', '1926', '', 'Paul Leslie', 'Redfearn, jr.', NULL, NULL, NULL, NULL, NULL, NULL),
	(503, 'G. H.', 'von Post', '', '', 'G. H. von', 'Post', NULL, NULL, NULL, NULL, NULL, NULL),
	(504, 'Inga-Greta', 'Förare', '', '', 'Inga-Greta', 'Förare', NULL, NULL, NULL, NULL, NULL, NULL),
	(505, 'Carl Gustaf', 'Lillieroth', '', '', 'Carl Gustaf', 'Lillieroth', NULL, NULL, NULL, NULL, NULL, NULL),
	(506, 'Oskar Frederik', 'Andersson', '1862', '1938', 'Oskar Frederik', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(507, 'Vivi', 'Laurent', '', '', 'Vivi', 'Laurent', NULL, NULL, NULL, NULL, NULL, NULL),
	(508, '', 'Kaaldar', '', '', '', 'Kaaldar', NULL, NULL, NULL, NULL, NULL, NULL),
	(509, 'D.', 'Chassagne', '', '', 'D.', 'Chassagne', NULL, NULL, NULL, NULL, NULL, NULL),
	(510, 'Leutnanz[?]', 'Coldmann', '', '', 'Leutnanz[?]', 'Coldmann', NULL, NULL, NULL, NULL, NULL, NULL),
	(511, 'G.', 'Tawaski', '', '', 'G.', 'Tawaski', NULL, NULL, NULL, NULL, NULL, NULL),
	(512, 'Per', 'Linder', '', '', 'Per', 'Linder', NULL, NULL, NULL, NULL, NULL, NULL),
	(513, 'Frans Edvard', 'Conradi', '1890', '1907', 'Frans Edvard', 'Conradi', NULL, NULL, NULL, NULL, NULL, NULL),
	(514, 'P. A.', 'Westling', '1868', '1942', 'P. A.', 'Westling', NULL, NULL, NULL, NULL, NULL, NULL),
	(515, 'B.', 'Kaalaas', '1851', '1918', 'Baard Bastian Larsen', 'Kaalaas', NULL, NULL, NULL, NULL, NULL, NULL),
	(516, 'A. O.', 'Wihlman', '', '', 'A. O.', 'Wihlman', NULL, NULL, NULL, NULL, NULL, NULL),
	(517, 'J.', 'Duvigneaud', '', '', 'J.', 'Duvigneaud', NULL, NULL, NULL, NULL, NULL, NULL),
	(518, 'W. A.', 'Setchell', '', '', 'W. A.', 'Setchell', NULL, NULL, NULL, NULL, NULL, NULL),
	(519, 'Alfred', 'Traverse', '1925', '', 'Alfred', 'Traverse', NULL, NULL, NULL, NULL, NULL, NULL),
	(520, 'Vilhelm', 'Gaunitz', '', '', 'Vilhelm', 'Gaunitz', NULL, NULL, NULL, NULL, NULL, NULL),
	(521, 'Valentin', 'Norlind', '1887', '', 'Josef Yngve Valentin', 'Norlind', NULL, NULL, NULL, NULL, NULL, NULL),
	(522, 'T.', 'Arvidsson', '', '', 'T.', 'Arvidsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(523, 'Edvin', 'Eriksson', '', '', 'Edvin', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(524, 'Jan', 'Grönlung', '', '', 'Jan', 'Grönlung', NULL, NULL, NULL, NULL, NULL, NULL),
	(525, 'Paul', 'Hora', '', '', 'Paul', 'Hora', NULL, NULL, NULL, NULL, NULL, NULL),
	(526, '', 'Fralla', '', '', '', 'Fralla', NULL, NULL, NULL, NULL, NULL, NULL),
	(527, 'S.', 'Milde', '', '', 'S.', 'Milde', NULL, NULL, NULL, NULL, NULL, NULL),
	(528, 'P. G. M.', 'Rhodes', '', '', 'P. G. M.', 'Rhodes', NULL, NULL, NULL, NULL, NULL, NULL),
	(529, 'A.', 'Schmidt', '', '', 'A.', 'Schmidt', NULL, NULL, NULL, NULL, NULL, NULL),
	(530, 'C.', 'Sanis', '', '', 'C.', 'Sanis', NULL, NULL, NULL, NULL, NULL, NULL),
	(531, 'H. S.', 'Jewett', '', '', 'H. S.', 'Jewett', NULL, NULL, NULL, NULL, NULL, NULL),
	(532, 'Josef Wilhelm', 'Håkansson', '1862', '1951', 'Josef Wilhelm', 'Håkansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(533, 'Johann', 'Mikutowicz.', '1872', '1951', 'Johann Mattias', 'Mikutowicz.', NULL, NULL, NULL, NULL, NULL, NULL),
	(534, 'Cyrus Guernsey', 'Pringle', '1836', '1911', 'Cyrus Guernsey', 'Pringle', NULL, NULL, NULL, NULL, NULL, NULL),
	(535, 'F.', 'Schultz', '', '', 'F.', 'Schultz', NULL, NULL, NULL, NULL, NULL, NULL),
	(536, 'Olof', 'Dagberg', '', '', 'Olof', 'Dagberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(537, 'Martin', 'Asplund', '', '', 'Martin', 'Asplund', NULL, NULL, NULL, NULL, NULL, NULL),
	(538, 'Håkan', 'Sundin', '', '', 'Håkan', 'Sundin', NULL, NULL, NULL, NULL, NULL, NULL),
	(539, 'August', 'Holler', '1835', '1904', 'August', 'Holler', NULL, NULL, NULL, NULL, NULL, NULL),
	(541, 'Adolf', 'Friberg', '', '', 'Adolf', 'Friberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(542, 'Gary J.', 'Schroeder', '', '', 'Gary J.', 'Schroeder', NULL, NULL, NULL, NULL, NULL, NULL),
	(543, 'C.', 'Dybeck', '', '', 'C.', 'Dybeck', NULL, NULL, NULL, NULL, NULL, NULL),
	(544, 'Peter Fredrik', 'Wahlberg', '1800', '1877', 'Peter Fredrik', 'Wahlberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(545, 'J. W.', 'Boström', '', '', 'J. W.', 'Boström', NULL, NULL, NULL, NULL, NULL, NULL),
	(546, 'Roy Franklin', 'Cain', '', '', 'Roy Franklin', 'Cain', NULL, NULL, NULL, NULL, NULL, NULL),
	(547, 'Jessica', 'Wossman', '', '', 'Jessica', 'Wossman', NULL, NULL, NULL, NULL, NULL, NULL),
	(548, 'K. G.', 'Limpricht', '', '', 'K. G.', 'Limpricht', NULL, NULL, NULL, NULL, NULL, NULL),
	(549, 'P.', 'Strandmark', '', '', 'P.', 'Strandmark', NULL, NULL, NULL, NULL, NULL, NULL),
	(550, 'Dana', 'Griffin, III', '1938', '', 'Dana', 'Griffin, III', NULL, NULL, NULL, NULL, NULL, NULL),
	(551, 'Otto', 'Degenor', '', '', 'Otto', 'Degenor', NULL, NULL, NULL, NULL, NULL, NULL),
	(552, 'G. A.', 'Geheeb.', '', '', 'G. A.', 'Geheeb.', NULL, NULL, NULL, NULL, NULL, NULL),
	(553, 'Lars Gunnar', 'Romell', '1891', '', 'Lars Gunnar', 'Romell', NULL, NULL, NULL, NULL, NULL, NULL),
	(554, 'H.', 'Kuhlbrodt', '', '', 'H.', 'Kuhlbrodt', NULL, NULL, NULL, NULL, NULL, NULL),
	(555, 'Helge', 'Bruun', '', '', 'Helge G.', 'Bruun', NULL, NULL, NULL, NULL, NULL, NULL),
	(556, 'Ferdinand', 'Winter', '', '', 'Ferdinand', 'Winter', NULL, NULL, NULL, NULL, NULL, NULL),
	(557, '', 'Wagner', '', '', '', 'Wagner', NULL, NULL, NULL, NULL, NULL, NULL),
	(558, '', 'Eggler', '', '', '', 'Eggler', NULL, NULL, NULL, NULL, NULL, NULL),
	(559, '', 'Dalman', '', '', '', 'Dalman', NULL, NULL, NULL, NULL, NULL, NULL),
	(560, 'A.', 'Zmuda', '', '', 'A.', 'Zmuda', NULL, NULL, NULL, NULL, NULL, NULL),
	(561, 'Otto', 'Collin', '1890', '1905', 'Otto', 'Collin', NULL, NULL, NULL, NULL, NULL, NULL),
	(562, '', 'Lackström', '', '', '', 'Lackström', NULL, NULL, NULL, NULL, NULL, NULL),
	(563, 'A. O. ', 'Kihlman', '', '', 'A. O. ', 'Kihlman', NULL, NULL, NULL, NULL, NULL, NULL),
	(564, 'W.', 'Mönkemayer', '', '', 'W.', 'Mönkemayer', NULL, NULL, NULL, NULL, NULL, NULL),
	(565, 'Gustaf Adolf', 'Zwanziger', '1839', '1893', 'Gustaf Adolf', 'Zwanziger', NULL, NULL, NULL, NULL, NULL, NULL),
	(566, 'A.', 'Braun', '', '', 'A.', 'Braun', NULL, NULL, NULL, NULL, NULL, NULL),
	(567, 'Lennart', 'Sahlberg', '', '', 'Lennart', 'Sahlberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(568, 'Bertil', 'Ekholtz', '', '', 'Bertil', 'Ekholtz', NULL, NULL, NULL, NULL, NULL, NULL),
	(569, 'Stellan', 'Rosén', '', '', 'Stellan', 'Rosén', NULL, NULL, NULL, NULL, NULL, NULL),
	(570, 'Dan', 'Nordin', '', '', 'Dan', 'Nordin', NULL, NULL, NULL, NULL, NULL, NULL),
	(571, 'Seth', 'Magni', '', '', 'Seth', 'Magni', NULL, NULL, NULL, NULL, NULL, NULL),
	(572, 'Oscar', 'Holmström', '', '', 'Oscar', 'Holmström', NULL, NULL, NULL, NULL, NULL, NULL),
	(574, 'August', 'Dalhem', '', '', 'August', 'Dalhem', NULL, NULL, NULL, NULL, NULL, NULL),
	(575, 'Fabricius', 'Müller', '', '', 'Fabricius', 'Müller', NULL, NULL, NULL, NULL, NULL, NULL),
	(576, 'K.', 'Hahn', '', '', 'K.', 'Hahn', NULL, NULL, NULL, NULL, NULL, NULL),
	(577, '', 'Beckhaur', '', '', '', 'Beckhaur', NULL, NULL, NULL, NULL, NULL, NULL),
	(578, 'H. H.', 'Johnsson', '', '', 'H. H.', 'Johnsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(579, 'Hanna', 'Nilsson', '', '', 'Hanna', 'Nilsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(580, 'H.', 'Ternblom', '', '', 'H.', 'Ternblom', NULL, NULL, NULL, NULL, NULL, NULL),
	(581, 'Gunnar', 'Löfstedt', '', '', 'Gunnar', 'Löfstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(583, 'D. ', 'Zetterstedt', '', '', 'D. ', 'Zetterstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(584, 'William Alfred', 'Weber', '1918', '', 'William Alfred', 'Weber', NULL, NULL, NULL, NULL, NULL, NULL),
	(585, 'Lars Peter Reinhold', 'Matsson', '', '', 'Lars Peter Reinhold', 'Matsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(586, 'Gunnar', 'Kellberg.', '', '', 'Gunnar', 'Kellberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(587, 'E.', 'Westblad', '', '', 'E.', 'Westblad', NULL, NULL, NULL, NULL, NULL, NULL),
	(588, 'H.', 'Greve', '', '', 'H.', 'Greve', NULL, NULL, NULL, NULL, NULL, NULL),
	(589, 'J. ', 'Lange', '', '', 'J. ', 'Lange', NULL, NULL, NULL, NULL, NULL, NULL),
	(590, 'Torsten', 'Håkansson', '', '', 'Torsten', 'Håkansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(591, 'J. J.', 'Havås', '', '', 'J. J.', 'Havås', NULL, NULL, NULL, NULL, NULL, NULL),
	(592, 'J.', 'Collin', '', '', 'J.', 'Collin', NULL, NULL, NULL, NULL, NULL, NULL),
	(593, 'Margareta', 'Elfving', '', '', 'Margareta', 'Elfving', NULL, NULL, NULL, NULL, NULL, NULL),
	(594, 'Carl', 'Stenhammar', '', '', 'Carl', 'Stenhammar', NULL, NULL, NULL, NULL, NULL, NULL),
	(595, 'I.', 'Brunnthaler', '', '', 'I.', 'Brunnthaler', NULL, NULL, NULL, NULL, NULL, NULL),
	(596, 'P. F. ', 'Lundquist', '', '', 'P. F. ', 'Lundquist', NULL, NULL, NULL, NULL, NULL, NULL),
	(597, 'G.', 'Adlerz', '', '', 'G.', 'Adlerz', NULL, NULL, NULL, NULL, NULL, NULL),
	(598, 'Pentti', 'Alanko', '1936', '', 'Pentti', 'Alanko', NULL, NULL, NULL, NULL, NULL, NULL),
	(599, 'B.', 'Wahlin', '', '', 'B.', 'Wahlin', NULL, NULL, NULL, NULL, NULL, NULL),
	(600, 'G.', 'Löfgren', '', '', 'G.', 'Löfgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(601, 'P. O. ', 'Cleve', '', '', 'P. O. ', 'Cleve', NULL, NULL, NULL, NULL, NULL, NULL),
	(602, 'Sven', 'Fransson', '', '', 'Sven', 'Fransson', NULL, NULL, NULL, NULL, NULL, NULL),
	(603, 'G. ', 'Lundqvist', '', '', 'G.', 'Lundqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(604, 'Axel', 'Arrhenius', '1858', '1950', 'Johan Israel Axel', 'Arrhenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(605, 'J. ', 'Scriba', '', '', 'J. ', 'Scriba', NULL, NULL, NULL, NULL, NULL, NULL),
	(606, 'Ant.', 'Göransson', '', '', 'Ant.', 'Göransson', NULL, NULL, NULL, NULL, NULL, NULL),
	(607, 'Karl Erik', 'Renhorn', '', '', 'Karl Erik', 'Renhorn', NULL, NULL, NULL, NULL, NULL, NULL),
	(608, 'N. C.', 'Petersen', '', '', 'N. C.', 'Petersen', NULL, NULL, NULL, NULL, NULL, NULL),
	(609, 'C.', 'Johanson', '', '', 'C.', 'Johanson', NULL, NULL, NULL, NULL, NULL, NULL),
	(610, 'Joseph P.', 'Tracy', '', '', 'Joseph P.', 'Tracy', NULL, NULL, NULL, NULL, NULL, NULL),
	(611, 'Jan', 'Fredriksson', '', '', 'Jan', 'Fredriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(612, 'Ola', 'Eriksson', '', '', 'Ola', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(613, 'J.', 'Hruby', '', '', 'J.', 'Hruby', NULL, NULL, NULL, NULL, NULL, NULL),
	(614, 'Selim', 'Birger', '1879', '1931', 'Selim', 'Birger', NULL, NULL, NULL, NULL, NULL, NULL),
	(615, 'Onraedt', 'Maurice', '', '', 'Onraedt', 'Maurice', NULL, NULL, NULL, NULL, NULL, NULL),
	(616, 'P.', 'Reinsch', '', '', 'P.', 'Reinsch', NULL, NULL, NULL, NULL, NULL, NULL),
	(617, 'J. ', 'Treboux', '', '', 'J. ', 'Treboux', NULL, NULL, NULL, NULL, NULL, NULL),
	(618, 'A.', 'Malmstedt', '', '', 'A.', 'Malmstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(619, 'M.', 'Fleishcer', '', '', 'M.', 'Fleishcer', NULL, NULL, NULL, NULL, NULL, NULL),
	(620, 'E. A. ', 'Ekstedt', '', '', 'E. A. ', 'Ekstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(621, 'M.', 'Licklider', '', '', 'M.', 'Licklider', NULL, NULL, NULL, NULL, NULL, NULL),
	(622, 'A. ', 'Voigt.', '', '', 'A. ', 'Voigt.', NULL, NULL, NULL, NULL, NULL, NULL),
	(623, 'Johann Andreas', 'Baumler', '1847', '1926', 'Johann Andreas', 'Baumler', NULL, NULL, NULL, NULL, NULL, NULL),
	(624, '', 'Brunard', '', '', '', 'Brunard', NULL, NULL, NULL, NULL, NULL, NULL),
	(625, 'C. Hansen', 'Ostenfeld', '', '', 'C. Hansen', 'Ostenfeld', NULL, NULL, NULL, NULL, NULL, NULL),
	(626, 'N. G.', 'Moe', '', '', 'N. G.', 'Moe', NULL, NULL, NULL, NULL, NULL, NULL),
	(627, '', 'Hegelmaier', '', '', '', 'Hegelmaier', NULL, NULL, NULL, NULL, NULL, NULL),
	(628, 'E. ', 'Bauer', '', '', 'E. ', 'Bauer', NULL, NULL, NULL, NULL, NULL, NULL),
	(629, 'H.', 'Vendrely', '', '', 'H.', 'Vendrely', NULL, NULL, NULL, NULL, NULL, NULL),
	(630, 'Gerhard', 'Lindblom', '', '', 'Gerhard', 'Lindblom', NULL, NULL, NULL, NULL, NULL, NULL),
	(631, 'A. ', 'Acuña', '', '', 'A. ', 'Acuña', NULL, NULL, NULL, NULL, NULL, NULL),
	(632, 'O.', 'Buehlien', '', '', 'O.', 'Buehlien', NULL, NULL, NULL, NULL, NULL, NULL),
	(633, 'A. F.', 'Vesterlund', '', '', 'A. F.', 'Vesterlund', NULL, NULL, NULL, NULL, NULL, NULL),
	(634, 'Olaf Alfred', 'Hoffstad', '1865', '1943', 'Olaf Alfred', 'Hoffstad', NULL, NULL, NULL, NULL, NULL, NULL),
	(635, 'Wilhelm', 'Siegmund', '', '', 'Wilhelm', 'Siegmund', NULL, NULL, NULL, NULL, NULL, NULL),
	(636, 'M. T.', 'Lange', '', '', 'M. T.', 'Lange', NULL, NULL, NULL, NULL, NULL, NULL),
	(637, 'E.', 'Ule', '', '', 'E.', 'Ule', NULL, NULL, NULL, NULL, NULL, NULL),
	(638, 'J. S.', 'Jungner', '', '', 'J. S.', 'Jungner', NULL, NULL, NULL, NULL, NULL, NULL),
	(639, 'W.', 'Krieger', '', '', 'W.', 'Krieger', NULL, NULL, NULL, NULL, NULL, NULL),
	(640, 'Georg', 'von Martens', '', '', 'Georg von', 'Martens', NULL, NULL, NULL, NULL, NULL, NULL),
	(641, 'H.', 'Nilsson-Ehle', '', '', 'H.', 'Nilsson-Ehle', NULL, NULL, NULL, NULL, NULL, NULL),
	(642, 'Morten', 'Wormskjold', '1783', '1845', 'Morten', 'Wormskjold', NULL, NULL, NULL, NULL, NULL, NULL),
	(643, '', 'Breutel', '', '', '', 'Breutel', NULL, NULL, NULL, NULL, NULL, NULL),
	(644, '', 'Yngström', '', '', '', 'Yngström', NULL, NULL, NULL, NULL, NULL, NULL),
	(645, 'J.', 'Marten', '', '', 'J.', 'Marten', NULL, NULL, NULL, NULL, NULL, NULL),
	(646, 'J. T.', 'Linzey', '', '', 'J. T.', 'Linzey', NULL, NULL, NULL, NULL, NULL, NULL),
	(647, 'C. J.', 'Johanson', '', '', 'C. J.', 'Johanson', NULL, NULL, NULL, NULL, NULL, NULL),
	(648, '', 'Hübener', '', '', '', 'Hübener', NULL, NULL, NULL, NULL, NULL, NULL),
	(649, 'Pehr Conrad', 'Afzelius', '1817', '1850', 'Pehr Conrad', 'Afzelius', NULL, NULL, NULL, NULL, NULL, NULL),
	(650, 'Fr.', 'Sandéen', '', '', 'Fr.', 'Sandéen', NULL, NULL, NULL, NULL, NULL, NULL),
	(651, 'Seppo', 'Eurola', '1930', '', 'Seppo', 'Eurola', NULL, NULL, NULL, NULL, NULL, NULL),
	(652, 'I. M.', 'Vaughan', '', '', 'I. M.', 'Vaughan', NULL, NULL, NULL, NULL, NULL, NULL),
	(653, 'N. O.', 'Holst', '', '', 'N. O.', 'Holst', NULL, NULL, NULL, NULL, NULL, NULL),
	(654, 'Jozef', 'Barth', '1833', '1915', 'Jozef', 'Barth', NULL, NULL, NULL, NULL, NULL, NULL),
	(655, 'E.', 'Richmer', '', '', 'E.', 'Richmer', NULL, NULL, NULL, NULL, NULL, NULL),
	(656, 'Lars', 'Silén', '', '', 'Lars', 'Silén', NULL, NULL, NULL, NULL, NULL, NULL),
	(657, 'R.', 'Mailaise', '', '', 'R.', 'Mailaise', NULL, NULL, NULL, NULL, NULL, NULL),
	(658, 'H.', 'Müller', '', '', 'H.', 'Müller', NULL, NULL, NULL, NULL, NULL, NULL),
	(659, 'O.', 'Reinhhardt', '', '', 'O.', 'Reinhhardt', NULL, NULL, NULL, NULL, NULL, NULL),
	(660, 'Oskar', 'Lönnqvist', '', '', 'Oskar', 'Lönnqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(661, 'Richard', 'Gaunitz', '', '', 'Richard', 'Gaunitz', NULL, NULL, NULL, NULL, NULL, NULL),
	(662, 'E. ', 'Eugenius', '', '', 'E. ', 'Eugenius', NULL, NULL, NULL, NULL, NULL, NULL),
	(663, 'Carl', 'Melander', '', '', 'Carl Anton', 'Melander', NULL, NULL, NULL, NULL, NULL, NULL),
	(664, 'Hugo', 'Osvald', '', '', 'Hugo', 'Osvald', NULL, NULL, NULL, NULL, NULL, NULL),
	(665, 'E. ', 'Niclassen', '', '', 'E. ', 'Niclassen', NULL, NULL, NULL, NULL, NULL, NULL),
	(666, 'Alois', 'Hilgart', '', '', 'Alois', 'Hilgart', NULL, NULL, NULL, NULL, NULL, NULL),
	(667, 'Paul', 'Wasmuth', '1909', '', 'Paul', 'Wasmuth', NULL, NULL, NULL, NULL, NULL, NULL),
	(668, 'Robert Statham', 'Williams', '', '', 'Robert Statham', 'Williams', NULL, NULL, NULL, NULL, NULL, NULL),
	(669, 'G.', 'Westerberg', '', '', 'G.', 'Westerberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(670, 'K.', 'Mägdergrau', '', '', 'K.', 'Mägdergrau', NULL, NULL, NULL, NULL, NULL, NULL),
	(671, '', 'Loeske', '', '', '', 'Loeske', NULL, NULL, NULL, NULL, NULL, NULL),
	(672, 'W. G', 'Lindgren', '', '', 'W. G', 'Lindgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(673, 'Torsten Edward', 'Hasselrot', '1903', '1970', 'Torsten Edward', 'Hasselrot', NULL, NULL, NULL, NULL, NULL, NULL),
	(674, 'John Alphaeus', 'Allen', '1863', '1916', 'John Alphaeus', 'Allen', NULL, NULL, NULL, NULL, NULL, NULL),
	(675, 'Olof', 'Norrby', '', '', 'Olof', 'Norrby', NULL, NULL, NULL, NULL, NULL, NULL),
	(676, 'A.', 'Schwab.', '', '', 'A.', 'Schwab.', NULL, NULL, NULL, NULL, NULL, NULL),
	(677, 'H.', 'Hornberg', '', '', 'H.', 'Hornberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(678, 'Aug.', 'Sandgren', '', '', 'Aug.', 'Sandgren', NULL, NULL, NULL, NULL, NULL, NULL),
	(679, 'E. A.', 'Larsson', '', '', 'E. A.', 'Larsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(680, 'Hernfrid', 'Witte', '', '', 'Hernfrid', 'Witte', NULL, NULL, NULL, NULL, NULL, NULL),
	(681, 'Sten', 'Eriksson', '', '', 'Sten', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(682, 'H.', 'Masson', '', '', 'H.', 'Masson', NULL, NULL, NULL, NULL, NULL, NULL),
	(683, 'Johan Emanuel', 'Wikström', '1789', '1856', 'Johan Emanuel', 'Wikström', NULL, NULL, NULL, NULL, NULL, NULL),
	(684, 'Arvid', 'Jansson', '', '', 'Arvid', 'Jansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(685, 'R.', 'Jansson', '', '', 'R.', 'Jansson', NULL, NULL, NULL, NULL, NULL, NULL),
	(686, 'H.', 'Holmberg', '', '', 'H.', 'Holmberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(687, 'Fr.', 'Lundberg', '', '', 'Fr.', 'Lundberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(688, 'Elsa', 'Borg', '', '', 'Elsa', 'Borg', NULL, NULL, NULL, NULL, NULL, NULL),
	(689, 'J.', 'Hulting', '', '', 'J.', 'Hulting', NULL, NULL, NULL, NULL, NULL, NULL),
	(690, 'Alb.', 'Andersson', '', '', 'Alb.', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(691, 'C. ', 'Müller', '', '', 'C. ', 'Müller', NULL, NULL, NULL, NULL, NULL, NULL),
	(692, 'Th.', 'Jensen', '', '', 'Th.', 'Jensen', NULL, NULL, NULL, NULL, NULL, NULL),
	(693, 'F.', 'Walkers', '', '', 'F.', 'Walkers', NULL, NULL, NULL, NULL, NULL, NULL),
	(694, 'E. F.', 'Dresler', '', '', 'E. F.', 'Dresler', NULL, NULL, NULL, NULL, NULL, NULL),
	(695, 'M.', 'Mahu', '', '', 'M.', 'Mahu', NULL, NULL, NULL, NULL, NULL, NULL),
	(696, 'J. W.', 'Bengtsson', '', '', 'J. W.', 'Bengtsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(697, 'O. B.', 'Santesson', '', '', 'O. B.', 'Santesson', NULL, NULL, NULL, NULL, NULL, NULL),
	(698, 'Georg', 'Bergfors', '', '', 'Georg', 'Bergfors', NULL, NULL, NULL, NULL, NULL, NULL),
	(699, 'C. J.', 'Levenhagen', '', '', 'C. J.', 'Levenhagen', NULL, NULL, NULL, NULL, NULL, NULL),
	(700, 'A. L.', 'Segerström', '', '', 'A. L.', 'Segerström', NULL, NULL, NULL, NULL, NULL, NULL),
	(701, 'Hedvig', 'Biller', '', '', 'Hedvig', 'Biller', NULL, NULL, NULL, NULL, NULL, NULL),
	(702, 'Henrik', 'Hasselman', '', '', 'Henrik', 'Hasselman', NULL, NULL, NULL, NULL, NULL, NULL),
	(703, 'Signe', 'Birger', '', '', 'Signe', 'Birger', NULL, NULL, NULL, NULL, NULL, NULL),
	(704, 'Edv.', 'Ellingsen', '', '', 'Edv.', 'Ellingsen', NULL, NULL, NULL, NULL, NULL, NULL),
	(705, 'Lars', 'Ericson', '', '', 'Lars', 'Ericson', NULL, NULL, NULL, NULL, NULL, NULL),
	(706, 'Olav', 'Gjaerevoll', '', '', 'Olav', 'Gjærevoll', NULL, NULL, NULL, NULL, NULL, NULL),
	(707, 'T.', 'Herben', '', '', 'T.', 'Herben', NULL, NULL, NULL, NULL, NULL, NULL),
	(708, 'Eric', 'Kihlberg', '', '', 'Eric', 'Kihlberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(710, 'A. G.', 'Lidström', '', '', 'A. G.', 'Lidström', NULL, NULL, NULL, NULL, NULL, NULL),
	(711, 'A.', 'Vezda', '', '', 'A.', 'Vezda', NULL, NULL, NULL, NULL, NULL, NULL),
	(712, 'Alfred', 'Nordström', '', '', 'Alfred', 'Nordström', NULL, NULL, NULL, NULL, NULL, NULL),
	(713, 'E. C.', 'Wallace', '', '', 'E. C.', 'Wallace', NULL, NULL, NULL, NULL, NULL, NULL),
	(714, 'Pekka', 'Bader', '', '', 'Pekka', 'Bader', NULL, NULL, NULL, NULL, NULL, NULL),
	(715, 'Gudrun', 'Norstedt', '', '', 'Gudrun', 'Norstedt', NULL, NULL, NULL, NULL, NULL, NULL),
	(716, 'F.', 'Filarszky', '', '', 'F.', 'Filarszky', NULL, NULL, NULL, NULL, NULL, NULL),
	(717, 'J.', 'Smith', '', '', 'J.', 'Smith', NULL, NULL, NULL, NULL, NULL, NULL),
	(718, 'Terttu', 'Pekkarinen', '', '', 'Terttu', 'Pekkarinen', NULL, NULL, NULL, NULL, NULL, NULL),
	(719, 'M.', 'Elfstrand', '', '', 'M.', 'Elfstrand', NULL, NULL, NULL, NULL, NULL, NULL),
	(720, 'O.', 'Swartz', '', '', 'O.', 'Swartz', NULL, NULL, NULL, NULL, NULL, NULL),
	(721, 'Björn', 'Lindberg', '', '', 'Björn', 'Lindberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(722, 'Ester', 'Wretman', '', '', 'Ester', 'Wretman', NULL, NULL, NULL, NULL, NULL, NULL),
	(723, 'Oscar', 'Hahnström', '', '', 'Oscar', 'Hahnström', NULL, NULL, NULL, NULL, NULL, NULL),
	(724, 'Axel', 'Wachtmeister', '', '', 'Axel', 'Wachtmeister', NULL, NULL, NULL, NULL, NULL, NULL),
	(725, 'Hildur', 'Wijkström', '', '', 'Hildur', 'Wijkström', NULL, NULL, NULL, NULL, NULL, NULL),
	(726, 'Eva', 'Östrand', '', '', 'Eva', 'Östrand', NULL, NULL, NULL, NULL, NULL, NULL),
	(727, 'Helge', 'Svensson', '', '', 'Helge', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL),
	(728, 'T.', 'Lundblad', '', '', 'T.', 'Lundblad', NULL, NULL, NULL, NULL, NULL, NULL),
	(729, 'Marc', 'Bremond', '', '', 'Marc', 'Bremond', NULL, NULL, NULL, NULL, NULL, NULL),
	(730, 'Gösta', 'Kjellmert', '', '', 'Gösta', 'Kjellmert', NULL, NULL, NULL, NULL, NULL, NULL),
	(731, 'G.', 'Ankarswärd', '', '', 'G.', 'Ankarswärd', NULL, NULL, NULL, NULL, NULL, NULL),
	(732, 'Lars', 'Hjortsberg', '', '', 'Lars', 'Hjortsberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(733, 'Gösta', 'Fredman', '', '', 'Gösta', 'Fredman', NULL, NULL, NULL, NULL, NULL, NULL),
	(734, 'H.', 'Rancken', '', '', 'H.', 'Rancken', NULL, NULL, NULL, NULL, NULL, NULL),
	(735, 'Johan', 'Nitare', '', '', 'Johan', 'Nitare', NULL, NULL, NULL, NULL, NULL, NULL),
	(736, 'Birgitta', 'Eriksson', '', '', 'Birgitta', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL),
	(737, 'Tuulikki', 'Rooke', '', '', 'Tuulikki', 'Rooke', NULL, NULL, NULL, NULL, NULL, NULL),
	(738, 'Sara', 'Landvik', '', '', 'Sara', 'Landvik', NULL, NULL, NULL, NULL, NULL, NULL),
	(739, 'V. J.', 'Oinonen', '', '', 'V. J.', 'Oinonen', NULL, NULL, NULL, NULL, NULL, NULL),
	(740, 'Paul O.', 'Shallert', '', '', 'Paul O.', 'Shallert', NULL, NULL, NULL, NULL, NULL, NULL),
	(741, 'Sven-Åke', 'Hanson', '', '', 'Sven-Åke', 'Hanson', NULL, NULL, NULL, NULL, NULL, NULL),
	(742, 'Kjell', 'Olofsson', '', '', 'Kjell', 'Olofsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(743, 'Siv', 'Muskos', '', '', 'Siv', 'Muskos', NULL, NULL, NULL, NULL, NULL, NULL),
	(744, 'Olle', 'Persson', '', '', 'Olle', 'Persson', NULL, NULL, NULL, NULL, NULL, NULL),
	(745, 'S.', 'Sivertsen', '', '', 'S.', 'Sivertsen', NULL, NULL, NULL, NULL, NULL, NULL),
	(746, 'Esteri', 'Ohenoja', '', '', 'Esteri', 'Ohenoja', NULL, NULL, NULL, NULL, NULL, NULL),
	(747, 'Magnus', 'Magnusson', '', '', 'Magnus', 'Magnusson', NULL, NULL, NULL, NULL, NULL, NULL),
	(748, 'Eira', 'Hiukka', '', '', 'Eira', 'Hiukka', NULL, NULL, NULL, NULL, NULL, NULL),
	(749, 'Sigurd', 'Sundell', '', '', 'Sigurd W.', 'Sundell', NULL, NULL, NULL, NULL, NULL, NULL),
	(750, 'Åsa', 'Dalsätt', '', '', 'Åsa', 'Dalsätt', NULL, NULL, NULL, NULL, NULL, NULL),
	(751, 'Eric Steen', 'Hansen', '', '', 'Eric Steen', 'Hansen', NULL, NULL, NULL, NULL, NULL, NULL),
	(752, 'Ove', 'Almborn', '', '', 'Ove', 'Almborn', NULL, NULL, NULL, NULL, NULL, NULL),
	(753, 'Sakura', 'Netterling', '', '', 'Sakura', 'Netterling', NULL, NULL, NULL, NULL, NULL, NULL),
	(754, 'Henrik', 'Hedenås', '', '', 'Henrik', 'Hedenås', NULL, NULL, NULL, NULL, NULL, NULL),
	(755, 'Sven', 'Hellqvist', '', '', 'Sven', 'Hellqvist', NULL, NULL, NULL, NULL, NULL, NULL),
	(756, 'Stefan', 'Ericsson', '', '', 'Stefan', 'Ericsson', 'Intendent på Herbarium UME', NULL, NULL, NULL, NULL, NULL),
	(757, 'Bertil', 'Norrlöf', '', '', 'Bertil', 'Norrlöf', NULL, NULL, NULL, NULL, NULL, NULL),
	(758, 'Thomas', 'Elmquist', '', '', 'Thomas', 'Elmquist', NULL, NULL, NULL, NULL, NULL, NULL),
	(759, 'Åsa', 'Hagner', '', '', 'Åsa', 'Hagner', NULL, NULL, NULL, NULL, NULL, NULL),
	(760, 'Peer', 'Corfixen', '', '', 'Peer', 'Corfixen', NULL, NULL, NULL, NULL, NULL, NULL),
	(761, 'A. H.', 'Magnusson', '', '', 'A. H.', 'Magnusson', NULL, NULL, NULL, NULL, NULL, NULL),
	(762, '', 'Follmann', '', '', '', 'Follmann', NULL, NULL, NULL, NULL, NULL, NULL),
	(763, 'D.', 'Gaunitz', '', '', 'D.', 'Gaunitz', NULL, NULL, NULL, NULL, NULL, NULL),
	(764, 'Lauri E.', 'Kari', '', '', 'Lauri E.', 'Kari', NULL, NULL, NULL, NULL, NULL, NULL),
	(765, 'Hans', 'Ullrich', '', '', 'Hans', 'Ullrich', NULL, NULL, NULL, NULL, NULL, NULL),
	(766, 'Lars-Erik', 'Muhr', '', '', 'Lars-Erik', 'Muhr', NULL, NULL, NULL, NULL, NULL, NULL),
	(767, 'Kalle', 'Huuskonen', '', '', 'Kalle', 'Huuskonen', NULL, NULL, NULL, NULL, NULL, NULL),
	(768, 'Steen N.', 'Christensen', '', '', 'Steen N.', 'Christensen', NULL, NULL, NULL, NULL, NULL, NULL),
	(769, 'Shirley C.', 'Tucker', '', '', 'Shirley C.', 'Tucker', NULL, NULL, NULL, NULL, NULL, NULL),
	(770, 'Sten', 'Ahlner', '', '', 'Sten', 'Ahlner', NULL, NULL, NULL, NULL, NULL, NULL),
	(771, 'K.', 'Glanc', '', '', 'K.', 'Glanc', NULL, NULL, NULL, NULL, NULL, NULL),
	(772, 'Roland', 'Moberg', '', '', 'Roland', 'Moberg', NULL, NULL, NULL, NULL, NULL, NULL),
	(773, 'Paul', 'Gelting', '', '', 'Paul', 'Gelting', NULL, NULL, NULL, NULL, NULL, NULL),
	(774, 'B.', 'Hedvall', '', '', 'B.', 'Hedvall', NULL, NULL, NULL, NULL, NULL, NULL),
	(775, 'Vagn', 'Alstrup', '', '', 'Vagn', 'Alstrup', NULL, NULL, NULL, NULL, NULL, NULL),
	(776, 'Felix', 'Schumm', '', '', 'Felix', 'Schumm', NULL, NULL, NULL, NULL, NULL, NULL),
	(777, 'Helge', 'Boström', '', '', 'Helge', 'Boström', NULL, NULL, NULL, NULL, NULL, NULL),
	(778, 'Robert S.', 'Egan', '', '', 'Robert S.', 'Egan', NULL, NULL, NULL, NULL, NULL, NULL),
	(779, 'N.', 'Alvthin', '', '', 'N.', 'Alvthin', NULL, NULL, NULL, NULL, NULL, NULL),
	(780, 'J.', 'Lambinon', '', '', 'J.', 'Lambinon', NULL, NULL, NULL, NULL, NULL, NULL),
	(781, 'Francoise', 'Candoussau', '', '', 'Francoise', 'Candoussau', NULL, NULL, NULL, NULL, NULL, NULL),
	(782, 'Dan', 'Norlin', '', '', 'Dan', 'Norlin', NULL, NULL, NULL, NULL, NULL, NULL),
	(783, 'Folke', 'Fagerlind', '', '', 'Folke', 'Fagerlind', NULL, NULL, NULL, NULL, NULL, NULL),
	(784, 'A. J. S.', 'Whalley', '', '', 'A. J. S.', 'Whalley', NULL, NULL, NULL, NULL, NULL, NULL),
	(785, 'Edgar', 'Wieslander', '', '', 'Edgar', 'Wieslander', NULL, NULL, NULL, NULL, NULL, NULL),
	(786, 'Kurt', 'Lidén', '', '', 'Kurt', 'Lidén', NULL, NULL, NULL, NULL, NULL, NULL),
	(787, 'Harry', 'Christoffersson', '', '', 'Harry', 'Christoffersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(788, 'Olof', 'Andersson', '', '', 'Olof', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(789, 'Gunnar', 'Nilsson', '', '', 'Gunnar', 'Nilsson', NULL, NULL, NULL, NULL, NULL, NULL),
	(790, 'Claire K.', 'Schmitt', '', '', 'Claire K.', 'Schmitt', NULL, NULL, NULL, NULL, NULL, NULL),
	(791, 'Ove', 'Andersson', '', '', 'Ove', 'Andersson', NULL, NULL, NULL, NULL, NULL, NULL),
	(792, 'Henrik', 'Hesselman', '', '', 'Henrik', 'Hesselman', NULL, NULL, NULL, NULL, NULL, NULL),
	(793, 'Alfred', 'Berg', '', '', 'Alfred', 'Berg', NULL, NULL, NULL, NULL, NULL, NULL),
	(794, 'Mats', 'Karström', '', '', 'Mats', 'Karström', NULL, NULL, NULL, NULL, NULL, NULL),
	(795, 'Åke', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(796, 'Åke', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(797, 'Åke', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(798, 'Åke', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(799, 'Åke', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(800, 'Åke', 'Svensson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(801, 'Torbjörn', 'Tyler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(802, 'Sven', 'Snogerup', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(803, 'Britt', 'Snogerup', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(804, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(805, 'Jimmy', 'Persson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(806, 'Lars-Åke', 'Gustavsson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(807, 'Anette', 'Carlström', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(808, 'Hans', 'Runemark', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(809, 'Holmgren', 'Björn', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(810, 'Aldén', 'Björn', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(811, 'Bentzer', 'Bengt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(812, 'Axel Samuel', 'Harpen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(813, 'R. v.', 'Bothmer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(814, 'Bertil', 'Nordenstam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(815, 'Lennart', 'Engstrand', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(816, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(817, 'A. S.', 'Trolander', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(818, 'Jakob', 'Eriksson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(819, 'A.', 'Aptroot', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(820, 'A.', 'Borhidi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(821, 'A. Edv.', 'Gorton', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(822, 'A.', 'Glaziou', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(823, 'Osmo', 'Huuskonen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(824, 'A.', 'Wiberg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
